---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: paperless
  namespace: paperless
spec:
  secretName: paperless-certificate
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-clusterissuer-acme-letsencrypt-cloudflare
  dnsNames:
    - paperless.47fc5c.com
