---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless
  namespace: paperless
data:
  PAPERLESS_DBENGINE: "postgres"
  PAPERLESS_DBHOST: "postgres-cluster-rw.postgres-cluster.svc.k3s-01.47fc5c.com"
  PAPERLESS_DBNAME: "paperless"
  PAPERLESS_DBUSER: "paperless"
  PAPERLESS_OCR_LANGUAGE: "eng"
  PAPERLESS_PORT: "8000"
  PAPERLESS_TIME_ZONE: "Europe/Rome"
  PAPERLESS_URL: "https://paperless.47fc5c.com"
