---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  namespace: paperless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless
  template:
    metadata:
      labels:
        app: paperless
    spec:
      containers:
        - name: paperless
          image: ghcr.io/paperless-ngx/paperless-ngx:3.0.4@sha256:3838b9a4260d23acc5bb63aed407138435e70b56e5806f4baa350ca184e57582
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 2Gi
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: paperless
            - secretRef:
                name: paperless
          volumeMounts:
            - name: paperless
              mountPath: /usr/src/paperless/data
              subPath: data/
            - name: paperless
              mountPath: /usr/src/paperless/media
              subPath: media/
            - name: paperless-consume
              mountPath: /usr/src/paperless/consume
      volumes:
        - name: paperless
          persistentVolumeClaim:
            claimName: paperless
        - name: paperless-consume
          persistentVolumeClaim:
            claimName: paperless-consume
