---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  namespace: paperless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless
  template:
    metadata:
      labels:
        app: paperless
    spec:
      containers:
        - name: paperless
          image: ghcr.io/paperless-ngx/paperless-ngx:3.2.0@sha256:22dc423ff48ac1629977dbf0c9625ba9f60d3bd1291a2ff173c65351984a14c2
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 2Gi
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: paperless
            - secretRef:
                name: paperless
          volumeMounts:
            - name: paperless
              mountPath: /usr/src/paperless/data
              subPath: data/
            - name: paperless
              mountPath: /usr/src/paperless/media
              subPath: media/
            - name: paperless-consume
              mountPath: /usr/src/paperless/consume
      volumes:
        - name: paperless
          persistentVolumeClaim:
            claimName: paperless
        - name: paperless-consume
          persistentVolumeClaim:
            claimName: paperless-consume
