---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-consume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: paperless-consume
    namespace: paperless
  storageClassName: nfs
  nfs:
    server: nfs.47fc5c.com
    path: /mnt/pool-0/volumes/generic/documents
