---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-crypto-global
  resources:
    requests:
      storage: 1Gi
