---
operator:
  replicaCount: 2
  image:
    repository: quay.io/minio/operator
    pullPolicy: IfNotPresent
  env:
    - name: CLUSTER_DOMAIN
      value: "k3s-01.47fc5c.com"
    - name: OPERATOR_STS_ENABLED
      value: "on"
    - name: WATCHED_NAMESPACE
      value: "minio"
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    fsGroup: 1000
  containerSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: name
                operator: In
                values:
                  - minio-operator
          topologyKey: kubernetes.io/hostname
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
      ephemeral-storage: 500Mi
