---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: endurain
  namespace: endurain
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: endurain
  template:
    metadata:
      labels:
        app: endurain
    spec:
      containers:
        - name: endurain
          image: codeberg.org/endurain-project/endurain:v0.19.2@sha256:092c26904028237b7da3bc205e15ede0c70b07084d86e582c3644f66b1cfb140
          envFrom:
            - configMapRef:
                name: endurain
            - secretRef:
                name: endurain
