---
apiVersion: v1
kind: ConfigMap
metadata:
  name: romm
  namespace: romm
data:
  DB_HOST: "mariadb.mariadb.svc.k3s-01.47fc5c.com"
  DB_NAME: "romm"
  DB_PORT: "3306"
  OIDC_ENABLED: "true"
  OIDC_PROVIDER: "authentik"
  OIDC_REDIRECT_URI: "https://romm.47fc5c.com/api/oauth/openid"
  OIDC_SERVER_APPLICATION_URL: "https://auth.47fc5c.com/application/o/romm"
  REDIS_HOST: "redis.redis.svc.k3s-01.47fc5c.com"
  REDIS_PORT: "6379"
  REDIS_DB: "2"
  ROMM_BASE_URL: "https://romm.47fc5c.com"
  ROMM_DB_DRIVER: "mariadb"
  ROMM_PORT: "8090"
