---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm
  namespace: romm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-crypto-global
  resources:
    requests:
      storage: 250Mi
