---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: romm
  namespace: romm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: romm
  template:
    metadata:
      labels:
        app: romm
    spec:
      containers:
        - name: romm
          image: docker.io/rommapp/romm:5.0.0@sha256:91f6611eca5a4dafc4f4a1d72a1ed7dd66a11375d939f28410dc1d1de0b80b1b
          startupProbe:
            httpGet:
              path: /api/heartbeat
              port: 8090
            failureThreshold: 5
            periodSeconds: 20
          volumeMounts:
            - name: romm-data
              mountPath: /romm/assets
              subPath: assets/
            - name: romm-data
              mountPath: /romm/config
              subPath: config/
            - name: romm-data
              mountPath: /romm/resources
              subPath: resources/
            - name: romm-roms
              mountPath: /romm/library/roms
          envFrom:
            - configMapRef:
                name: romm
            - secretRef:
                name: romm
      volumes:
        - name: romm-data
          persistentVolumeClaim:
            claimName: romm-data
        - name: romm-roms
          persistentVolumeClaim:
            claimName: romm-roms
