---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: postgres-cluster
spec:
  instances: 3
  storage:
    size: 10Gi
    storageClass: longhorn-crypto-global-single-replica
  postgresql:
    synchronous:
      method: any
      number: 1
  managed:
    roles:
    - name: authentik
      login: true
      passwordSecret:
        name: authentik-role
    - name: freshrss
      login: true
      passwordSecret:
        name: freshrss-role
    - name: gotify
      login: true
      passwordSecret:
        name: gotify-role
    - name: lidarr
      login: true
      passwordSecret:
        name: lidarr-role
    - name: linkding
      login: true
      passwordSecret:
        name: linkding-role
    - name: mealie
      login: true
      passwordSecret:
        name: mealie-role
    - name: prowlarr
      login: true
      passwordSecret:
        name: prowlarr-role
    - name: radarr
      login: true
      passwordSecret:
        name: radarr-role
    - name: readarr
      login: true
      passwordSecret:
        name: readarr-role
    - name: sonarr
      login: true
      passwordSecret:
        name: sonarr-role
    - name: wger
      login: true
      passwordSecret:
        name: wger-role
