---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homebox-role
  namespace: postgres-cluster
spec:
  encryptedData:
    password: AgCXOZebycSI9ZATeFWnOciyZLsl+o1H2MXW6IZaB73qYcyoXzJZwxsNfRSpMggwJLBAl/X9DfWNg0a1ZW8ndPzymfwn6/LdUG/9LhHcyNggKROZeIEK9QVaqYt/E6VOZ1Knfjw2tvVUtl9r9Eis1dmVUdfxjSFiWgfoNk+frTVcE07DHr1dNquLRAgya4i3sEGHx6ff1p16P+jJ8S5zKPn6Qd+49jDy/KlLNWuByGWC9WTzAWiwoZKgf6X/y6j2YdCLghMZOC05kvj7JPNagnca2CgIwFPp51f6T6Ufomst1tzuCa62PQHmwMbBWCm8bNGetoYZUqAhv1qaaLrmK7k3I27mUd3d78AXb4Bpnb3w4eA8m+jO7TQMWtjoDabiH085yZMahUYAI4Zx6+bK5SsHLjWjzSTM5mlgkDg8tI+kqAHYLfqC95ihg8za+BOxsqpcNDtxP2vs1Eud6WCkxQfBQQj/VAcgs/oEMdAf1r3L4ELxxHrqc4ZI53Or8kjI+QNSQ+70YxLYZyBfvzJV71L0PRlhWZGk8rKTKhFpIXzCxCqVZVPRDUTlNWWtwQCAHX8Z5imTlbwNEQOZYXhylz0s4fLctFJGZ1rUPDavYhrTEN9p7JoeggM2n9oocRhM9/O27D8XmaBMCJtbKDl9z+V+cl5cSom8KB/O5+ibihTdvvlDZ/BAApNknss7C/B6eLZTkloEfREAVTg779iiFuGSq05uOs2vVd/h4VG8+hO8iQ==
    username: AgCU4pDCndpv5Co0XKGYhq4ZswAwmc8WJJgzTpzfAYi+Kb3LsI6QnI89ngRaAbHLioJPfUe+EnMZfCrlbkOZv7qZatCJeV9eKka1HDRCEUxl8uALmg6DtObK7Lu2x8/KtuWaR+vNTxhGQO8oM7LrHQWBgIeazWHmtwNtEsIoeS6JlfSqHslXzhWVBJsdwSQnEWrIaPZzi0/zpnyAjUT2QsH9wge7N/NPzc3c3zPylREL+Dff18Jrxub0lBqwSvqdtdWWrKjPqfJw+x9vGQ52jtYObk+m/U4kigngYv2aIGnUjqx+NiX3ooV/VTKgBLT0ABOAJ7FtgTZXoQHCHE7rlQoKWda3RI26KX2w3MnFANrVUpgQhkR+XbC92A59SryKCHQ3Qqh2417z06RfSClZ5IorU+J19f2GVNwGE96h8mF4EzBPl5AKgWxP6ibHyagHsXd3RdiywVZDfYb72GGGC8d8SnnbO8NlVxVKzelTek272MqM2x9YLPMqE7mECVDobgBzkoCfMTV3ZrU9mBoWgtw9CdfTv2QR6zIzkRnFoIIcSPNJ6SZSjyNi/4J1erl5OD3kG92t1sgmTxk6LK9daqe46o9toM27DqDQAy3dU2avXt8tiFEF4pDKAtkwEPA1hFla5Ph8Dbu5xC0z3TOyKgQTOcH8BCsZFsYFgWZEVeUCXPq7q4ZTki38Z7EvDwHTQcNqXkAcpgaw
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: homebox-role
      namespace: postgres-cluster
