---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowlarr-role
  namespace: postgres-cluster
spec:
  encryptedData:
    password: AgAMwua2eAtbAjFDGJaieCdfI84/pZI7avWwWXKcwVRw3iigTEfzhF8R0Pj2VyG2h5tuxZYKIjLXn/GW/ABhak+ETRKDBI/osFjln/5qbonDcNpesTBo3AjbC/TWldkI2Wm/qOMF0unZuXzMPLkhCrhXM8cDvHinenGnu8tD1g7H+6FBrJ7ykY5c8+rEw/Qe4jLBpZGVxHJAqBptvfHxynqs0zeRa7BLmRlQG/iD1WCkfk+SvGVsMelh3sQM/E68y2r+Yc4t0An4Zv9usWRskATZBY909YNLvP2cLBv6p+sKU/JaAf0xX8A1OZh3aESn1IbN1RjgyL1ZRTE1gPgLEXFF1mWYtKwUyD4MnSuv9XPJBjl86O9EZLTBNmA3SDPGq8xuExyIf1S3Yu4LBgv5UvGT7MVHlwJRgDVl7Xd+9k6caa0JXA4SRt+NP6jqiz4Fcr/FxEHryP70HFdNmgenHuS1lec7e8Gq+N+q+79eUqhZNCrGd4WPn0Fazk9/4mg415XbjyO7QgFQoKQQFsUej6zzvzIWQ42xCSUvCGgd4bncjJmGSjcsg8dvXqokEGH6yr4MeEfegD3C02VLBMKRpAFUjsaD3g8/MKWJGdRIm8Xckp2ONgVvaW7OScFQUg3w/Sr5YkDZNZ+pQ3X3rn1FWACLplS3+uISN9gioibnb7M6VrNjSnb4I+ZJnoS1yozN2FLN96BTjzS6cRenG6+zx4SLTgEdMLUG5y0D9PUrYG2ALr8=
    username: AgCsOzWwiUku+iLJV6XqIbVv1a/UR9sCDKP0wwJMQWROnQlmM1N0FYoBcG/SkXQ3ZyktThW2dJ8uGudb5YTVBAyM2jN79ml4/WXbcEZalaVnza9FAHZwdc6WN2ARFf3RvhHPzdRSadWfji1TySDt4XGqGktyJch8nSdBmHRDZNLF7RkcsqFecqPw9wSrk77CyfItaNI4W+1ZyfQlKcNipPVivUkpCn5Gdj30KLgRxq0MOsi7D9GnJiz3V4cMuzySg98aE1WVsq4A/UP7heTf3aGpWh4f1/p+MvT4r1PCXv4SEyepWOVCpC0EQz/chjs72Tww5rmPW3UPio4o6pJFUkv3Fz+E6PhE9YDvtH/noauP8frx1gsFFGcG3ANaRa7ygdeEoxPKRD6afZSsTwYx2nGALnrmbCd00OCoUFSEvcg41hgcHgnJXhSkVdTLRUR9vuOf5kevD1LsA6OrG0dGNRS7ZIDEowOKZgvaJLtwvwOlBN/8cAN+e46NImPbGGpjsfQ93lssn6ng5LPfuLGXs0HW1anLAw6P4kO/jmOsTNJMtvpZHimG5Ty2PY9wZW3kKnipUeSKVYU1MASAOq/aC+BqRgVtRRn19zfR8rEkFKgb3pczYNmwP5gMjEvDN59VM3EzgFam+WfWIgjmEmfemNSRuVYrwcngKpU7GUQzbjKnFfb462Rdv3wpWGsx9QEmFeYcUot8U68TiZA=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: prowlarr-role
      namespace: postgres-cluster
    type: kubernetes.io/basic-auth
