---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airtrail-role
  namespace: postgres-cluster
spec:
  encryptedData:
    password: AgBrqHKO9EDZqrppeyOiaEaOjSEQFwBZo9dwCadPuh7yR7Xk4xCIos8+r2FDqvQxr/oZK4mjL4ezHYEnrUqWX+oqloFJfy8E/FKXaum7Fwyss+GKP3uQct0F16IBYl7kWeRhdnr1McDETnvsyunKgov/Faw2OhCCncGj0QBcFDAmRYg8sDy4IUyG872d9nf6EJG/nbnvzi3aNrVr532ZZTMJZ3VXUMtQfDhGZlG0Usf6ABwhP65RhI1cuh+QoMEFBBo5MYgOEoUWUPViy9x62lB7pPDFKpbQMngs9uYebPIM0hOWiIDCOQrd1kQ13q4WGgENZipROV2I4Wc0KZ8IbC45nV+7nusQroJhrpoLxfT5xyV3RV41qM0qiYwLnUfTZkBwt2NvdwkIbAL1KhEYfdipQMMpCLGGJnN5AYAYcKseymEiAIxBhY+Hpu+5rMzjSe6AZb/9R4piueGfwNK/2vX/sUoGLsxQu1TthyFLL9yG5d8keMBYiD7wVbr0ZXjo2jRrTe3BZefR8Qtch4WKTxebaiM7ppZ/uDFjnvBBN0Td2NRrvUj7H9W92HFvrli4CkL4i9I4NtsdGB4FT3Hfs2WvdVKGPZ4NeN5XTDTRT+gSUgFWOwQ8AhzslvqH+VsJNdRxsc/NjRGXi7pMYO96J8IX9IZvpX/aeLUPmiesvSZoST5snB8PRDRJmIFZeRB2uTiRgHqOMVeRv7r11lLRYYThTZ61kYRGCRw490dccw0QJA==
    username: AgDNwVjFo+tGQSSqoJmdynLyG1Vz0ZtJSMfhQn4pe94xdK74oYk/TXsOhX1mJWhNXOmP7u+k+diWtz7k0TXorYhMM/Q7GJI/OtlS5AURQevAcuxbFhKurTCiztsm6/veFE8QAIN/9CDWpzmx9psl9IHAC8185lV+t1Cal94Oq0pn99me9tT0d6Q9lH+1K+Ax22cDNEtF3QRxUCPALrD22WGJrDeJyqKYmBPN9gUwLugew8Ly6xH0+fPUejrVwDdjadbUaYomWFWKq7Prf+hGVq1Ly/0yI9H/a1Zdp8TgHFIeruVZaPFQ7o/n+2kvyoFkZ2MXHcB7jkn+m65ZmW8sZpXqRGv/9GQkf4Abp5PQLPMFK7hr0OItJnE1PCV8cS0vJ9lHOciNtgX9Vx7G6utVOIoGRaAG/FlNAYSXnsUXrxYsETm6CcoqccyUP3huQoxHBntSGbOyGtpjRSqncJJRLwcBc2BQGzGRsdoAR9rITd7T4s0FGSEsi5/1e7cUMp60ntgb5LTXbT3RysNaNKMej/Ldu569hxcER05CDwkME81KCvxcQjldELyb80MFhiEpYNBsVZKlHYUyljXwFdbe8dHYizwWk81qj683ujefhfGJDQoRYTS7JSzFfM/Qnz03eMJx4IxyxMdDswyX10ft2qb4PPn4POdjik1s/MwikvGrwX3RHjcfj9D8pUH+sx+lFN3SMeDjFeXZqg==
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: airtrail-role
      namespace: postgres-cluster
    type: kubernetes.io/basic-auth
