---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-role
  namespace: postgres-cluster
spec:
  encryptedData:
    password: AgBO5faaVRFEJyFh65bDJOcAvYzS3qgbHs10tWNTkToZ4T2VZpa60zIsZARZ73UlawnQwV7QkbLfoZYCG9XX+BKF+nVLSOZjHhYi9Q4tkMjRjqbnq6j/lM5zYSKuC9UajKUZ8ih+N0LwK/ZCKL8bjsAhpMjIDeHsnI8KASHrPgkh/2NJvv4m1cOb/vW9fKmCajlQIPcWhZv1SV+RQVt71ZIPu/js3O12SAc1Jg1wCDsHWSSx1z0vETzqxinEl4sKPdKaj47R0GVVpXHopiMVXHYYp/9ROdcGLWxkkFQLIyAsZdkvJwRiqN187eVNruF0iUL/65yEgGBI0UCiSCrJ+iV3q5BgKn6V4lXz/994V/TymV4mZ547oKiwJN7P2497bw/GEKV2ZUD7Cv1ZcfXDH3DjB8tK1VHRkCezfzpxjPX1x2bhk5Mmbvq5yDDCzfT8+ab/bKZJ55Jfm0DNYXzGcU5M7fP1ViTrJH8xTgN1U717Wh7DWcd5b83ltv8La+ucy2u7JZ/L69f6PdOsxRR68B8EB2ZuJIemCmM8Typc+ny3CVaEnx9s5VkYcUa1pWNLjW4ndPB64nP8pu76wHXJ66/Fx8ZUR3o6NMlAgE5WxsHx4qD+t7cILWOCEAWokXEsZOrSYysC9wMeLgqUBi9pKiHC0QN7/EtHP+DhuxPl7viN2Ee6ct6IbTXNSkt90tuEL18I13i6sYRglMgRVUVJeNJpaOhIOhQmnqc=
    username: AgC7kzPliZjl5/FS7Xk6cLLIFV+Dc7iemsDVck2+2Tqp3APKEV+vPKGswQg5ZdlYZ0xIpvd4N38yNjxCrX+kPbiVaT4lg/U7lJMhjQy0HRijNvE1Cn9Bm7S7gXkP95SD0FkSZbo5FERkLF5V77TbLpcOOBxsps7KbOy4YRXe9nPR0uLtG5JrjRHBoSwL8V0mHBOvKxfZWm6Ofil4hLkh8NhDE6hhdojEmuJcf64Y5+ejpAtZ/erR4PUPh9CyCt5WVPuJ3kNBDIeeYYa5C548nB/peQ1wi+dGxPjRnWhxT6/GBTLoiSYvUyl3qTiH+iN97kOvWdANy15BK4tmcAQbCNcEObeHpiReCV+5yOseynli/Qfd7h6+pF+owJKZWmyxnkc+UxXJ/fVYfN95x8PuJw+s5mXZM77H9kvzbeo88N9QSbqInZGASSdL7iNReMe57QJ5Nbjc7l7KouKSkEgLuJ8hCBSD7kINcsao3L63p9arYQz3ni1rAmUaAJAM8NwgtF0UycCLXz2TUWeqGWlbVpuc/3Muw4kT/6Ag42kdRnMyqdCwa0Jrj+R2Ltx9hIZjTRoQxebslYcuDXbwpEzJ+iqIEdpbUlxsj+POLfV3yx0xyN5+prHJM5qb9oVmBVxkY/TDfewvA7Pqlqi9QioVrVTvixPn3+2cwTS8yrfvCjj+0Otrtl8yNUsMJAkx7YpdZalkuXBwleYsPAA=
  template:
    metadata:
      name: nextcloud-role
      namespace: postgres-cluster
