---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gotify-role
  namespace: postgres-cluster
spec:
  encryptedData:
    password: AgAglVmvSKueBNFkzAm9H+5zq59TaeyYa96wFMszaSJIekP3R1aeHRhbRNFuX1Q+zu2wARXHrDWL2ZzlDaZXeGIGMCdlZybQITElgDMLLglmFP33x+Hv2vu+q8rM/7JDFi9nPYw+fcNdkEyBdz8T8h/4B+Zm59RlC2NlfWl+JnCBBIIcEdLAPWz8pBMwRRjLhCIq9pBy4E7ezzmlGBMS3bgtRa2r2OrMrOK3h0rOuw4vcXNrLctfUmMTR9DBzO0tuZL0S5OJr4skIFyjBXst5icMIiXvVbzZX8X4PBJx/VCN3UMNPqkOuDXhThu3EfagUOrz+eYwS7THGMa/wKOIJVvFT4Gg6QVKnzxaC6peDtOucZJ+kBDpC2HHumvv66Nf0w4VUvKjE3udCVXvm9JuvhnbBCLgbY9UtfbMSSZ/aiajBuVNzv+CbMFEL5rRgMm6KmnKgevZ2CRqc9+sQLJMjr31D3r0j8FX6FniHzMaet3PRIkZfm/vaTxKdahHvFtI+P3nFoR2UwXu1BG/85NA15wNtW/PqpZoHezk+s4YtMvaWngD/xq48CakhfG/P3xL1E/+8Uaev8NVpF7UZ8LQz59gRAOSrzFNbmUhxLsBoR2mr5Y0XQvmlMap2EQ91Rd0Q7iul/EvjYD0LlewAocSpctZAahIOUa4vuZWi7eMzDgfFhzleCiIqCcXn/CxWTsEMOc0MhikLCoR08P5I78ae+xVKTeMXqIha/Vp
    username: AgBiuzblqFXo3fupSzuEzzLu0aH3e3PBmzOXfpdf5KZIUX4EhjyAake9ixRkHiF3PTPBp9hRZyR4O17ZuMWyHCzpoWtlVLLgJl8XYBTnKOX2+byIVXgjqrW1y38IPmgsyWM5BqNugDnSK6t2pO/TnCbQSa+GDkf+KhzX/dJ46n2xoBakUlO/w5BhPy9KAdV0xC1pwPpY7s44dgvF7CnN/hZNs65jIbCA5FDKLyf1MgbXySMdOfIA3eiId0dhg4XK2jXQNRbhzrmVjXp7fGz9SFxQhby0qN5fkTnyZu2cY+OQze8vZgLKDsSDGQlVs79meSWP7Qxgolzr5DYOB89MxYlp6yFrUncu31x5T2Ly+3BherOb5D1VYTb+z+HZv+vpZNCfhZsqgkge5XfM4B701uD1Fx+R1rEc/8kpxDq01AoqF7Py5MxJn1nScZ7cxK1Z/SOYNoEiOg3PNF/J6GkZIZr5KjA8Cr0G+oEr/zi3cUvI6MJCgCs9u9B8r/19CfzrHrzg5MeeWH4Ov0EwED/KM8xaOIMxcAhJ7gnm4RuUIY6sRFBuTQp84SMb/Jd5NDMC9JQGf0Xiv6Em+4bTFmX0clZn0Xo0ZSJ6eaaAkT8TEDe5qy0yBZ6CrIv3hpoOMLhHZlYcSmU6A30llmJWHRI4ugsZx0noM4JGY2IrrC33O+7QqJYlajf6NiRQ2TPsZuuUU8NR2RNnIFOI
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: gotify-role
      namespace: postgres-cluster
    type: kubernetes.io/basic-auth
