---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: radarr-role
  namespace: postgres-cluster
spec:
  encryptedData:
    password: AgCLkimCmmMk11WeRRbqGr/NbaUTiPTXCmEu4uUGF9I8IrhAFvY3nQiEOkYfjXDub+qxCGXvkn2XSLbRcRHYs2MHE+JX/D8iJdHxh8RH1EKO1eQAYMeFKN0IfXh2d19J8UaxxVt6wn8z+InVINRWvbfj+nXiRlwLLi96/B7NrFNDvd9zxvZll/0LLRJp/3bxkLUi+u/BK4F9eWhF8aoBEHl/GZOkzspYPKk20JsazZovTXx9BzP+xsYgxu0bfuquaae89vjapLUyHDfreOVcqUhp7RQXEnclPhrHStAfAPJeOA4NB9yRnlrkve4eRhem1i/lz4ih5QFaGQE0yrTohA+Vj0GRkLDMhW7Tz1hQZaZtsmKWNfA4COh9Dw/z0VhEuBgIOYdgei2MrS435Q7CmeDTpBsnY4Ro1kyPzgIEO3NrPXaf3qoo0YdMj9wmWFp6rQnidAiJeq+bvj/gCsb+tUTHCTydA1yVgl3V2h4tx1LD9RSJD04/rNDwyjg06zujcSFFYCygWwNcLEvuU1lyF9csF21hHl9TBpQbzGKk6g7sv8modJm+OKFVmjupWzVr273YPe2J4jytjWvJRVkc+fxBQfVYABOX57cNNjhmqP52zv/rSJHSfbygbmCsOp8PnWuX7y7DQuVKGPBl8I2vMOyLmFk8q6B2iyxZh9zk/wbcgIpd65sFiX5UDetgULp+Vc7wp5ILy6gOcQpVlRaTibqiVPQWGNXZgzaDlaEGoAKawy4=
    username: AgDcY6S/TvwbMkjLWumZXo6P8rvSLlr9/0og9Ymrg3bZbXCrRvmb6eqsk6wIQnqjnr3LNNqKsqUiSjDQ26NxemDspc/7qa9FoXCyCbmLkCPN4W9pkrq+VAPdSB8T1vY2cxbGH2V/IerTavhkTQkBzUtkNoihFmsncanimLT8UCESRKSE5HmZ1BbDtOECIEh/qrzVU81bcXlzqh2x5RcMgHpj9fWiKQ8eJ1saJpyEwbgyHP0zjNTGHE9GeQ9RDNx7t22bSe0eILIjaHbc4w4QEoDbCrjxDO+AYUZQuCrmEet3I1IjDBvnuDByQ9G6Y1+JuB29fnjGRWxDVzLuCysxAokPtim1tWkZWKSBXPmIcsS5CpLcYLgpd6fjtEyoXghCCjxvoMJTaY/3h3JnYgoR2poPt+afjcROQC05Q2D08klyEzl4WOVG5Cclcs9t2AzQc1UwEpzlS8rgJKqcZAoD2yr+YElqlparXEyRYoof1nZB22pCJkMm3j0MH0RtUYaoiAteznG7pxEzcBeqOPBqfa+uD1s6LMdDj0mf3wq6pvybYFoV4N2mnw/qzzLlmWpDf5h+EEHboP5WvIhqpt/TmclUa35W8NHS+A39LVbkCKWyKi8QszxDviuvT1LwxYqptHDINtdFWwqi5lWgHcb2BQCjWZKEB6Ree+2az6P6ytTwgEnxJZQCVTATxd04EC3dQanQUPW4a6ak
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: radarr-role
      namespace: postgres-cluster
    type: kubernetes.io/basic-auth
