---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: readarr-role
  namespace: postgres-cluster
spec:
  encryptedData:
    password: AgBMlxKYfL+glv/8YA3BLU3O/sY14YGtQpudLC7/M4XY6xEoo3u7A/zhRqJA90ZJH7gQwSL1yC2thuAW3d5JtnkSyK3Y5PEzs0g8Gjm47IMY8hg+qm0e0TmRngyQH9+LXUmCNFWysDKPQr39b4twYhdmvO+Elm7u8QDGpco1UEgxiAUvPa6oZZZepQ9lubK75imteGm13xzUpm+q89dSxm0tzO+hHz1f3VV+rTCXB2J45OPkbnhp3mxz5C/DXTYCuyJs5pFpMYpuwJantaTAcFXyoey3pgDYoCKqoSL9bFsdbja5uYyDXf+Qav3X960z9IsFrxJWfI4FCiL9+nGqrLWg39DhPUPwbfD+hj86L9Ksb/0qGri7xyVUw7bzFydxzB8eLcgDu0ntuJnTgRnYN6emwtLBFz8XmDsH5t/qFEb7d6eZsSfPr0tTy2j5BTljDRmdRNWDVPSfCXexhdawxb2LxD7loP55ZFdaF3il1YX1qe+uCi0TFas22gAgxqQIxLJG0C54P3SXQYWaMw/5IiBoEk0+PO7lLBlrFniHruvYMpuZZcS5y58Ul7gAoHVY+hLovAl50EgJXJHLmCblsB7/S2Z46BUjLKTw3F9rK1rzup6oA45k8Cpcb9cSt+peztUYhIEiS5x9Ap1ZtAGnflrtFrdtdVLVVCbzqvCyisUbPRgPMIq7QIHvak/3/aiFbgqe332yHY38392U4VQnqRguJvAsvIRtUrs3QMh2sNq+3BM=
    username: AgDjg+rO3JCB1P7clWFo+iTy+vDvd344xcxwO9/ND4YKqXix8jWpp0/amHqtEMcq6U/O2YmBN8EeKF5hyOsuPqpqTQDlh0gBf0G0vqahp0XzDR33GXRN6zwPtvNjra42p7nftktiZ6PanfrZ2wle3mqmY3RgDzv6d6vfuY87wMuN4+BHirkhfg0U2FS/9/2ANsTyyFDpikB5AD9dgpXy3fYB1IOTovbAyxloRZCWve5pMTiLcMkFJ8eHc4G8lnQtMYs78FqFwk0V486/d8vDtbA0bVtgf9t5uQoXFLnTrLwm5IB+lTJKoNgYR75cNc5FYdRDJbZajc5Wi5xEQV8p0HsuiQxwxJMjESOSNbvBsEIP9InHN0dWw/2qLH2oAEAcqyEaAJDQ3bXhNrWDYb6EwUhJ9jL8Y0pciRmHMLBRgiHuyEFCX2p8dx3RoDJMb8vqBUhqj2MwLXei9sMdZ09oXT/Eluv4sDQpCi7u+LX90N6/aKACtLQ7ltRX14PHo4s1AWubGutDMnZQSr7FBXnJ571c3FcaTWjTnE3MUf2FQuHfZ3bQN3sq7hQcL3izgtCokxFKwTbL1/Nk475SBhkWyWLzTKj63AQcbOpJPvJ4zOC4Z36rOKOdoHgWVGYQI2wi7uWUbjNMSuLMn0LTfnFC0iMwVXXZ4F9qDhojVMePGLSmJwZrZntl8sxDj5AnuX8EHJJujflsWlln+A==
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: readarr-role
      namespace: postgres-cluster
    type: kubernetes.io/basic-auth
