---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-role
  namespace: postgres-cluster
spec:
  encryptedData:
    password: AgCiM5oUfBSRwd5orZQD63qr5t/TgdFbLCsEwCuJpaVMivrq17QDuCzxwIHhM8PH58uveStWwI/IS0UEJZvFULoujAJHbmH2TiiVSPfOmUfg9+u8ICQOkUIGLQy1QHZrQMBoGM3M9FXFj6WbkTXIs6hkaZNdljVBSdyYYRD7Sm28bvABRDHcV7Ifk1b5JLIKfUv5EQuCd1VIVdYYH/+RlfLciMMoFWytVy/uxiuxW+RvSqvuE/R8iQT4YbkUr4X9yl/PcWPJXLyS9xUg4Q6nIbCr8UNRPCHcEql+JTMQ1dEhsyPJrwEQT6UvMY/EMRJ+fF/PuaDZlwdAV7e2geCyqAUbFh+/0gOV/rWWD1mbcJpW2uTLtHODziJJsPd47WDGH5xO1G7eW2oY+JJ+W2ujtI5wEj0X0OFvEd6408oxzB6hoZ3lQSX7iBren9YFjSAqVfuGY0xcrXRrR8xzkStxSZg/L1lfLoAaZ4GFJO6FTpGr+66EGwuqqqGgev+TvkKVzx8BsjHJy/HK6pBURZQk/ZGKVGpELuvg0aI7PHkhgRyWfSnJsVK0ztai2eL/RfIBvVw1R4tsYphZDo+UBiZZEfT2qc40/jAVmBiNHHFPcdfQafypv4sdFDQ+kUbjL/c0cAV79HZapZ7VxRWpYSzszXAMHCUoukSeem8MXjOWPcaAWmG93S76l0lGSaC7XJmhqLBt6UWJoJIPdy/MsAzCd8Ux83u6xX08O+Dz3hWvNbRRkg==
    username: AgA6WMQPpalLDX2a7RJXHOq3Hy6jEXaDSoYLEu556naPAZOxNGPp2ps99KULMTXD9EGHVynonTZrEYwzw+3JgsiIsZUnPc2Baq9cs8PE9+2yPH7v8ryzkODnrbH1a/PFzpDvoLykxpe16dm7ZRqHtW6Z4D5SNbkAHJbjQ4su5CEHnf2DCdqxaykpvYmN3g9tBk4AxKnBivZqXvuSOLCK5QE2Gt/Rw8ux+dMDmqBTf/GZFKkTvy+rGGZbYbd70F8ugUMZBDhYaPE5Jk/5WfrdNM9/UQmwWpK4Tc+fJ1ZNkSOlGlj0sC5a5AQpV6E6HpYjK0GOxp8SUpn+UdLNyXC5b84VhfsY+LS2N0TglBXtOR4Ki5VR+z1rLGNFTrD+o9jCnvpuGwfG4HJuHhBkQs+RM02RKntG7ghekp2xIR/l7iKfxV/2UdhkzBN6HasQrXKbYq75+qf9wO19l/fqqI0Fcc00FKDHM/+YUtYTfgRW96dBaMNCg25x1iNG3zDg3tqgXX+zAmksJaaHrljZ5udu/Gm4eIaf6rJ/kF+26iJzkBRFeMC1YOoYPj5EMiKUJtUm90t293GaYNQU4MD4pRP2KC2hRjolvAQENwX1j/gdVDY5DKWxpdOc0tetoUnc89qxV7kNPUMFj01a2AmvkqC3dcqNbuYxC5rO/w0nTNuxZfnBqmuDWvETxOYejcKadXOPyYVW5PKInDep
  template:
    metadata:
      name: grafana-role
      namespace: postgres-cluster
