---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarr-role
  namespace: postgres-cluster
spec:
  encryptedData:
    password: AgBpkunZVito68s+X2KX8mxndelf+3lZS1d1TVOAWGIwFIzmfYM5C24+5KXDoV0lAAPmCSf3WkMqMOMOWF3jQ1e3ef6FhbeENhPdLBnz+UDSW5UjE/NRRVanqnmg2m1KMcDz4SHqXFRsSjo7210o4UOCyoFNtJum/mLo+AnNABoQLLP1pKG/H2dli/brgNfeYUkgk6clLZCb6axMFIEiYzlTix7jILZeXgRsbY4WvBYA//8mlPfckY6/4YCJqLJeLf+l2LcR92QdmX8UHR2AMyvt1XcBxOTbkLyLS02AVo90YPBjBudT3kr3TyRoiUMezRY0tVqU+WywC0rahvY2RH6/+frYFKYQYNox2HqvJv6RWJgWc4vaSdX5YIMoi3vVSzDaQUdsdwKAwjCikGAEvH+3FkutBwCPQyZCeAUTCw++8iIWgYZrvMd5ZQmWdmgZdKyW7qDfIurr5FL7ohg4po+rC3q+ecC6C0GZS1PfLTT40AUUKkJFs7fJ0JQ3ADRpdsWViwXO8Lj4wt31VqrdTLV1yyC4HFuCZiODuDfYCzwpkhBfBxZXeIJpQ7ZHKdJyPoFhSq1GwQCAaA+y3+jV3IKdsMrtPzC39Ju7Xlp5JnMPuq92+0NW2FEPetBy8kxPGb2OLcvc/uHYEfxtUchv0ryvmNDJ9vYAInNjZCfExFntL0xx0U3yllR/5bUmfDIxg+7jCtbYAEGLm9IkzvV4jVdxtKmWhBdVr32FnI+tsCvzFZ8=
    username: AgBp7EARWmLCGwuGkodhLVWgbN/Ncj07n+snHnYy1rEwhCEsyTMQE1RnVEx4eqnZ704LFDnpvbZGS3fOMuGZpiMeOTj6uPT0ADyWFuyEawSgGrtyI57zFaDEhaaqYuLN/QeQEvB5oOwfjT57mCjsZuTPiOaUhOS7zd0y6YriSHKzne7Csj01MufHVlM6DZ3FLtIaREg5OzdB85hHkhw6oD8T5TnMKvt4C1eDTxJO/Efnw4oMOaoXdKurEhCbNG2tiNwaOGNEZv869ab53bYoYCOR4YxIaDmUR5Twn15I/R/N7j0JT3l/5ecVeQdPq6g+127TIm7jYwfI9C9fbT61hd/IIRQQgfOcdHmcJvrXM3Z5KTiOnrLqtOdqLbqrhiUIs9ecQF1RLUmZsqH3A/kJO3akQkTD0fkUSjSUuJ3ZDEcoqIFVKHqhXtBzoJltI6W/HABrMSU6G1lU8Gok5g7hLLmpnMw4gusbnbrakJZAXQkwTFOiefYoh+hKW7YJ+VGCByckqEb4Uq0Nk7AJAyFl3rly7e5RYVwB0x4WZoE+PZVbVds7MuYT8aUTtegkPQ9S2y5NGqLXLqrtuGI5uOAMgnp7V1mhv9tYHcDlD3qzkXyuOuPxMHo5siAcNYNUOz+YlyvsBeqek64Ui3hw+pCu8p95XX7IglexKlnuQXv9zkVtAqT9wIbGy6yE2xx/ws5ytnijjgdV2tuU
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: sonarr-role
      namespace: postgres-cluster
    type: kubernetes.io/basic-auth
