---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: firefly-role
  namespace: postgres-cluster
spec:
  encryptedData:
    password: AgBqEu+GbMGxhB9bFq7OgmJQ9bDL8sp6c4WRcKVi/QOLAUtQdZSZl4sPmN3y9A0ftMFwBMaAxFerMWscD66wyquaYNTkt4YJ3GhEqMW5KT8PSCH7NSq2LFm8GNFxWiXQUi58RocPLQsst6UvLklnJHCjhjrxAwm1B1IsMDIuhDPaoC31ZZQVHgdg1TuVLHyFJt6dSeZDCxBxTBeZWNyRAbdA35kOZBxaXLpWGIPNVFDCOzOg1K6PRhNH/sTM+swZXjG4OFdsHRSZc1vY+uVNUBeI23HSSsbljuzSONQJG3H/C3f/snIAYrJWR7q7qYaSbEkrea0r/GYNGqWUkn0Ohi9EloJVkjSSsvYchpx9FlX7hCHwzIfV0Guyz8EOSWJllVA96t5mPJpz4ZqsuJ3tBEL58iccmQ0FyMaWcpqmaS2szhFQLW0r8u+fSDQMvtzQVIyxqo7RwaZ0m59nPyzZrkgbNotNA9YJwrQi5aLbKhhMxEJOUpd1SJfu2+JNqhmEL0KDiuto6mD0I0S4GAVeQsAAY43/BnDMyxdefxrvYXvxiSSvLuyCVMoNLWzBEpgYiZN3q7Y9qW+g6fxffQxcLq5V1P4ILUC3B++1lYLKx9g29IulqzjWdJVl2goDSPht65abuugy4xV8J4lx803YswO4Vz8VOr2ESihnX2hG0hTr8qbxp1TeprAtgLxtlSaYDjIdQjSKeh0FEl4z48YZcQO/iW0U76RipKA4
    username: AgA/jY49u6qsZuSRRe6YWL7jT6B4w7TiTP3/unGN/NonEUOoLa2qNQJIaUlgoR2PMWPUpIKxmMOuhNKavwxfrre+0wa01AnyrJEPen4341bMf4OCCUKNnbZN6eFsZeNofkLTfHp2L7YHiLRVR8gLZAgDA+WSaBK48A0kWCfah3usuoohOSfsvB/ENNCBzW3uhUBKHOIMilB2N+N9qgGIN4xeI7P3zrREJiPViwGxlY2MDbo3JiCf926Abl3ku/0ogttzHQg77Xs+177FKomdtHcm88SgyW2Vajcq8dyZufdY+kcAElwLLjzqVrCJ5beQJuS5h0W0HRuiBxvxhlDndBb+5l28g8+bv8CtucOIEbGP0PkdL3qzCkuOYuGRcYr5k4oFLreEyVy7Gph/+BS18oTb7MwTAt1oTz/9QUyZXngBUCXB2Gj9/tVwz2IAfgJryq/Fc0t8XZLxEp1A9wb+mVm1lZAYm57IHsxE44E37UTv1y1tr9pXyeb5Ob0qc1yq2qxsJ6gVui9xEUeGANlfJYxz/qMu+6oMt2nAhYmYBpWfVsPJ0ViPOmcwaGxxFgdjC+DwW/v0iThyGxwQcMavm7/ZoxBd+LW7Ig6I9jmL8vZsHkmVTkyVRrQ9hxB6w2fk+2fQL6weG0M34awKouz8hnuYCJaeabvxfiHlN3SmZTs28NxlQ85gMP7Gl8dNTSfxXTH5wQfHMc9t
  template:
    metadata:
      name: firefly-role
      namespace: postgres-cluster
