---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-role
  namespace: postgres-cluster
spec:
  encryptedData:
    password: AgAe4Roq++HD6x6Fc+APmcjZ+dxktqo63BX6ctbTgkJZ3Ce/sFFCymBHU4PkgrwoxDYpMKo15OElWuBryJFNM7ou5YkdiObBrbUgCW7uitxy0BIbMdj8G7F5ClBExPVDmOt/Os5FRZUOKdRKw9jMZZldoO8YIjYqgArRF4pXthYRfxPiJn/fR/DFlWHnrU0OgHI+gPMooLkAiDdGJz3MremL8T68WbepCRKg3O0i05/VpD+zTxZ5Jc1hSah7LVUe//c5G+txsl7ASzRjsRYzWDeGvRtAwvcN243N9T3VltEgZcaALCKO9MC5rAWYxT42F1p6bHsrdlW7KtUz1rG7tvRhFxwP5/X1P/pCZwkTw5nQCXqTN1GnX2gbwroUBkdWpjDQ7uY7zhPyinOdXpOEVBhra1qeE7JDaF067Mo5XzVVcAo+4UBZTdBNxH+DKROFkWHdpHjIG9zHwss435xm5ITwy+KGv4q9pUOpJdWwkE7O4P6tJRd8Evtyfm2od9/NZ49HUkuyLQdmNxl/6D5PuZ24hs0nfZNHid3Gnbcw0WVW35FuspZh2iONIZKwI3X2mulqOVu9NzKJOLnB1uTasSwGvJqRuNqu3EKLcluBEqjW5jP7kv+kXM/Gu2cAbCXkxnPtKYhYfe3Dpg0VF/rcWzuyDU8XgNdk54SSTbYsDq6QaPxRG+U8UNqOFaB5TvDtzjx5cL++aNJQmU81Qr8SLAUzarLuh+C4YnaQjgxkFiOs/g==
    username: AgBKPGxwoKdFmsbQ0jw5trX7nu7JcJz9zuxkevnDDCg1jdjDU3RQpndULAwwAMdI8TVaXG4penAiwi9j0YvvN9wp3dko1xuKoTUaqsdcGY/jC5J4iD2el5RQHK1qfkHpX65e+Z3s/bxylI+IyKRG6ShQJu/zHKIsW0xTKR8ikgsYXGzGjF3jqbZXwQAru7ztStJZBE518dPjy8NcmfngZiIwjkyvqWDv5wnvhOYk4bL8pYOFv13ajEHX6jDGNt/lnuho+zyGRAh6hwQwqtmMR+2FDItNKPjNo0JbJP4NG435A9RrY7uAMW4nMcsnLd3wpiQQhQMihh/KMlQTDxIwci1MUot1SwyHQqhyFCE/X6WgASjEIh/MT5u/Ce3LAi16kD8eu7yb+jnZIn9BIPkMlCJ036pqqEisWh4Ye+PIXAmEp4xz96lwkAHvkmmz/DHqsT+h/5g1u6E+y7XwuKxBKZIUbLBa36cDN2/ykTFpvgaPaMrC3za4qcQ3RjgbmkfrzCeCBxh+w/QVt7L3kvhaPaIvP2M15Q0LDsI078gvDs1+J8q3lacVsTm4fzFaPV96q4qnSouTFXy+IlK5ccSSwVcfYmOYm1txa0/fttOjPRf4U6e4khia3efgxdN3/U9LzDEkXPxVCbvBZLwcSQV8DAnWtwLc8vubjKJkoBYdrkDRoD3jALQ7NqeGjpmTe5hVmQSrZjwI/XQVQkc=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: paperless-role
      namespace: postgres-cluster
