---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: freshrss-role
  namespace: postgres-cluster
spec:
  encryptedData:
    password: AgBEUWaZSRe0P+RaBMT83ADJAHBNCzw2eRnGjW6Zxnyot1MWR0jtEfl8sOaHXrGxQo1O1np5xmU2nZEvhGhlCzCpR9ADrIziA4ujNUZ+64Kn2cGrILWsWnC3vNJK1Dzb/XWi4GpH7is2XyKMC59HzcGMMC8eFhjTo+pigZQWdjFrT3LrXpJpoi46dtp4rmrJIJkp9YG1Hv5+hbvcW7WG138iLwt2/QbFghdy7YeTSQ2Ffhu/t/dGVgbdTexfT0CjNmvDEYYzwvBFJuUPzZlkr+pJdCOPhIm3+5bIXjTDHWMS/depIkg3Hhhn7DEqQVSFxi3T85+otVI3SAWml938j6/3itAEHktpS5gNsIz78Klu2SHiAP7jghGc6NR8WzE8BXX7eH7RgTcbJoVgFGfQsSV4ecWcrH/IezjFMDt6wtKiajl45e2exEW7GJz7ZV6e0puzO/6lkR0e/+yFLbt9UCzBbZl80O4/v/J+cMo1mHc8AKOB/hLSTxuq/sBUpZI61y+OKg90NCVFdrxEh1ctD9yDQHCa+lxr8DOiyZw5GCW3Kt4KFXTCsCNZLzkIn3kWr/fzwSKr6KqwB8TMGSMYbJzq8dF//47zQdPHyyYN1obrCdxUaNFoH13QzqqVCykG8/3Kc1n/voMhnAPOMTfgyMPUlHxznu3FqNXJVG8sCM3dxnoCd/8qPl3zJWLr2AkojgV+c2XgUKLGLwHXccUsxSstnRGZ2TMkkICM
    username: AgAOFmk7WNvYK4pJ9L0kN63WlQyK/GKJcgR2sZL1IEiT2jWet3HKCkm8/LJFEfTzI6rweNOIeHdfePKQUkLpN1aeY7gGofwyZ9Z4DK6SS3JUX/8wDaccvOlYd4IALtKOU/4PJ4pQ1EiQW+UVDL69+oLUMwaUEm/grBBScYFMvetJp46Lz3c5i5Do59wC4hbYMwWI00Dpe/QL6QdHm65unMdS3gcw/MxHdNc3q3yofPz3FiIUTWvxBXr8rk/Isbsdrl70geh8s+YGgV9iOqEt4G4CgViRNGib7K8p5IQee+0upCSZEuM7QQ7/c5BQXX+GgrXk/LbNeQoASsebu6n3U9xtJlU198r5UbOY9QVODeOnmZtdlEakp6IDWP1qt5YXRAq82Z842JNbpabvpZB8zBFe7fB6GHNElV/hAkjDO5zb7LsJ9e80X/c7YMvIBDgsvHIVgtuLgAMSEIDXQ07V3T7Zm4WtDrNDKTXRTp9Tvwm/1g7Y5JjYIYzOyHFxMcP2TRzj96xoSTrwOKU/XrzmIko5Vqj+mL1roz93REI0RmWMVPyxYe+uQBcfIstB5/Scyk0xPffP5h53kO4HYI4Hb4haNp/RfcIrkwHd4u6P6JhuR91rYR5ZiYk+EXqxcaR9aKpH12/I60VAYWyK4lK+tMJmJqL3Ed+Xi4FBnexd/oRTRXC3OoUPHj9KUQ2/2Hdj6L3bI9Px78BcdRU=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: freshrss-role
      namespace: postgres-cluster
    type: kubernetes.io/basic-auth
