---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-role
  namespace: postgres-cluster
spec:
  encryptedData:
    password: AgAIY9T+6AixfuWoYTzbm56ezTINJe+izTSozmxLj3mKQAVHaymr7bxuAGYahYs/vSaur/Bpv3N02hF2kGFZCpdWMK9x9doiOkLaXwOl1PLkaud/wjZrQIn++Vvc6ZFAO7Ik0uwPAfcFUEFMvXxR7brR5X5yYvwSBrWHFK9zI5canW/H9P36K/cWWRjnAzM+r2PEV0xjrKJY5MyoVsiLRi60uoEGbrNVo+inPp5LmiR280EKAITadFznBp8mg77vn7JXLRcADuj5/KZk15lehioyK6tkWEdvGzBm47WPnwTDjXfPuXDz25WC5u6KYvafEo/+NXdkLuAgeCv9egUZ4aaxR+IWQPM05Xf7Q3h0wN7s3ZPricWnGJEeCSbr30Tnkpk1Se+gd9nm+nLXvMXCnE+5Fk3xMzNRF5WEI9XiR3XdajpeVamJibXRjj4AIOHr5ig4g2AbA2CxZG4MLHBNfgINi65pDNfHu23gTBSmjZnZVl4ESKI1B+BscU7toDzmXTe3KIJV3iNU0DXxiXyuDQHfJVBMge+HQN7NOgeacpslzefFyobb38cGRNT2N830ESYXGz9HeDoMNQUX1z3Jq+EBlVKsUdzdkVFrEPJ2/O3GwxL6nC4P2pbUpvqbWz3kcfpzVp/9jwSpzTTJTRHCIKXd3F4nDOmtpPoj0Rr27GLRqy3h0BJpTgoJe3yPoQN+V5vzeOzq6ppqN34bJJjNKeOxEoG9CDUywSBE9jNJjfUg3w==
    username: AgCgKpMZeis1F/emiuSY0tnF6sLjFvUYk23D0JPpCBbXXwUWSciLR8uaezCidGSoPylgZhLzNKiLew6U07po7qpaEOlN3E+IJY4bpFVpHhJAFbIlcavxuwacc8KzCGkbaAAqvfPCjsa8fxCBg8f73pyAaBOkCkaZTf+AxrthLjpBiKm79EwaRZXZb+6rgeDqW7KPZa0AQRB2ZVnt0Hv7tei5N+b5TBAdOPG7Xk1tw7OMuaAbsFAgeApULUG1c8Qb1mnZLIZDQYkRd5lOqYfS213p2a/2HkTECZIUBoaULCTuTYIun1Rx2I1CntyqLDAJChYMmn4OsGnHeTPeuvl9wH6PszNrA2Bxw2Rsv41m3bZbIy7dQj/aZNpj+YpR2WbxeT8Ytlu2dcCMu8JFJ4xMmIFt+6kGZ9/WhKKSmFPyNW4JbaXIqaUTHgFNriZPJbN3SC6iOFJUxClfNq9Btncn6x3r5tSCZeYp+Rzho8DcDRarqpwDMLBz0agJY5nEhhnkj4QXUU5z19x1AFWmyZYAqQbpdc2DLBJHyip9c7fGU/5LsEdd44IjJutn44NSAh3NJtrmo0u4BAt/Wm5b3oyNohWvxBrAekEkoX0XS1kaIOoYb+SztqgZNp4KW0dv49sbHAWcvzfO1dx8UxXTJm6K6AMNqvfGMM6NcP5aad84O8m8KZTBfke5c5fq2U7KLX8ScL2Hiu3X9/WSqv4=
  template:
    metadata:
      name: paperless-role
      namespace: postgres-cluster
