---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lidarr-role
  namespace: postgres-cluster
spec:
  encryptedData:
    password: AgB2KG3SayJItpxNF3KYwcsPndeKfDdnmTM3k5tY14JnAuZxZ0Vco8xsAkWhr1AM8lYLbm4LV6OluFkRuQELHiOfptl3AT3Kys3KatyFxck75PDFs9dOhBKG6IMQeCMJaFbOSc1fqlt/aN61sb4ZYY4REnOSm1+QDfVutuBlLFqSf8KZmwagQxu3lJH3dUV4K6V80WidNovg43Sqqmi2m7VH5QtD17TvpZPsxvpNg0tB7tDEqMR43Oc/7JqjGMXOokDSmL81ak4FXqWVXG5FIUtC0i3xw8hCwIc3c6L0sTnichm/P4pkTuxmPaPPaju/UWvM3pBm5rJ+ZZVleZUU0jSjCHb15CG19pRpgf1QFriZII8T2HCj43rbUVDXhXnKk4IiMGl+3usRabrdVEFHbvkFmF+LRta8LKiNfZHlFB3+m9gbNeCONx9y6+DtzWuCoOWDlKMMEc6gxu5djMSoBrn54OZeFUfK2eBZTWoj3+xvRNJdLg8J5gfoD/GLltMtVtHjn577qwAg6zo52OmXay2v/Q6sD1M9WwbAqC6OMjsq/dvoesipv9StUZOOBoVJ/7q6Z7xBCGXljjk//wSYtmmq8KBtM5/fguJFH54Ae0WWMpuezQBmsLX0cxJc8Ekw3xmQ98Bj4nhGAR8aq+8JgPOhgoU1aD2EVpimFA28RN2A7Vvh/ntQkWCmEfRFJCO8boN3HWz4dZkhHcB7UEPkaQot2Pz8FKHVZjtiEWD3SCstoVQ=
    username: AgBo/NcizZUeNQOFa98KOf7rJa7JkM+B0U7D9PYxGtR+LlHauWymQ2R6vM7ac3As+5/EQyq8Rr0nst5gCm/qunqhbnQ7d1iLQfw1APIzggfW2bgJnJQn9Jnw3Kt3ocxI/oEtEwLp9QMkBpdCFwjgO1VSLE+x+AOaSPS4Kau9MWFeqJuYo51YmUslgabI3Wvgdgy61kI9yzQvJFVI8/v7AWQyQfxKGhcvE6T1+aelOnYCGczCrd5lVaYZHn590AbMxonfSeOdEtVzIMv9SQGysuJ92RZNGdQokxTecWXlF56WloDQxFafCu6P1+km5xLMg/trfAYzNj9J696lZ+sw4zPlbOKAgB1MInnkhlC0u7sw2VK+Vd5FpqjvqnZxq4DeWGC7dsQJn6Ay8GSuzal4ob4Q2LJvK6IWNZvmOopaed2VeaAAijQ69oHi3uiey/B9p/3ahJdcusJe1R3BrtwfiXR8pBkpjhVM28gaz6JPShK60bSMdYaIAxf+/T1mIVPlnfShzsTf47T4xO9n+y0S+0tH3NoANj49VSNcs3VVDclJWMeajpQuGQzcM2lRh2258XDISFDMRmK43dplFFtfmdZMlPzh+U7BEt2TcsUj41liktq647+9v+UahvvGLLOjV4bhHwT7CR0t47Aw5ZBMT79VICpZ6qCtFTiRn1X6sbF4RwOEn2+fEV9E2g2y2IKX+AuYoOoM7o+C
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: lidarr-role
      namespace: postgres-cluster
    type: kubernetes.io/basic-auth
