---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linkding-role
  namespace: postgres-cluster
spec:
  encryptedData:
    password: AgAiz/hlKYEABB5v7xLh6Hs90cE65+8hjvZj5gKbtJI7wcxlb9TDepG4VCxFSkve+JyljZCueAwTLKwd/IeLLRu9RL8YELIYK5VR5UgMjShbITWChENtQ6CWLHGNJUcDSSiPyLqJDOp1QB+xlSpT9Zem++VwdmoS3kbfA8TL/7K+cbCSKTreJqdSxdHdXhgvCoSJzEDnq9MAd/jjyySWCacPPsLIzmLLoIk82yTNzTvI/s6lM4LV1QFsmDqmM94DBSnzQAPcr3Hw4MGfLnTwsDmT0FeBUVjuc8493o+tJSbs/ubODonZ3iidsxTXEuWnmq/fFl+T9/oSR1RtzYGmzLq08zTDBayQ9sWAxWPhRx9unLtu877XbheOcPCjpdFu1U0woOxdRnRTG0B5UaZZ8rUWA6L34azyb3bP9ILtvYIED+GUfiaEkhR73ZB9CeptPTkrkam7dw31aEBMe8bB2IHGkLGXEs85KNO4EguVsfFvWB7m1L/sQFgYqEitGrX+EQpby9NhT1t2KAJtjbAUU9jbcFQhYbwzgkQLZwZZlYRw8PNNtv5TFzRelRMnTByNZHR7F0SgxcmKZEyVRP1sQpKdFPe6MiCCUltY8nNUm8RBGsrWxRnYH0sYNqrlZSFqrcRiHPsoEVqxn/yLNQk+VYYb7mMSQ2H8AHixVwpeduL7cxpIxdLaUB4ZOCbALtHM3OsjPWmoCZte5nb+TusGWM5qvtZHca0xI6G4
    username: AgCZml2ft4NmQ8hgcrtqKPCEh9zXZNTI72PwB44jImGNGwNzV7WkvNKVK1wXTbi1ItjuzORtiHWy6yE04DWTNJJuMfSV/mIm0vrQRkXNzhI9ZaVkXm1kT4cTX7h3kC5PHX81eG1T2Ukd/cGF+DlO6/rSsMTKCnJWeqki/j9pEgZkjhV5u6XXYXecUwwTy36vxOk26Q0+0ykdODzZAN+YzqfH2tEq6aYdK1qCL95ybqezdWvr6+dsYmeOo0HlUaPHwScTxq17D+n1WsymzVffWidXeATTpDzlovXu6+46/V9KwnlRDp0uuBfw/UIDqDzkW8Lx/fA0M8qKPJj7VSq/xqh30fyWP1QuSXE6SJzXqIg4x+tB+IvtVxrWPUKwjRtoTXjNfC/wZON0pu+kRLIwKLFlUNm3bGFHMa7Zo83nq9l7rY5DNYi4b+KhCNgFSvxnTFWdWk65ieOgv0BUpwZEhOPIhPMcmvi6tA1/2WL87vYic9ModdJ86NKmRosV270qMQ4K5jaVGl8eBohl6zyuVFudLrNNMpY9hiFm30hLcdajL5RcswJWjLfyzQU1YsvjL1xXL5kjifqbepr6jE/MP4xfdwfyG3ILs4Ysq7WUQFjAvrrF5f83tLPC55z37eKwDCe38KL+251CDFpXcIAH8qIOKPVM/842BKNCvak3bKF0n0zrAlpbUjnJaLNcZhAWmDvco9OEPkclatM=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: linkding-role
      namespace: postgres-cluster
    type: kubernetes.io/basic-auth
