---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: endurain-role
  namespace: postgres-cluster
spec:
  encryptedData:
    password: AgAo9UIGWaUuu9qhzUOWspRGofMcyB1bd7elCuUYSVIBPbU8f5yFta/uiwKJ/bEEjJbTskA4zCAqQ/WxrBP4Q38zc/vOzFlJp7HwihNXABAhw4sKMkvS/I/6qImO3JJhx1bZKZHdeNqCSYO6gGylMtcS6UytUSGXPK8ss+UF024e7vD9NCm1AwIfgI22KnS2mKpxqhe3NQY7QZ2urLbkYtgbP/x+JNTeskdrwihJ8i42Nb7xoY7L3dmjEL93xuFABIisuvAsquY38qr8fMOX200+CG6cEoK5nZmjcKJT8vtYiwFO6SmITRaxqkQkjYmcM5oMCK52IeEksNX/WjvZQSrCWiffC+2yb674YKh+XucR4kykNoRT7p8ojR9n/ARBriat2SOhwTyjPhx0sEt2QwqtiBiP2FHV8YZAyM7t2UnknV2r/DJg00IF3nOlj4ZM2ruGQTLQ6WHFPewiKEL9kGlUnf3WA1UF/u/vOJl0EI/vKTYv6H8zLTcV9dAk4OqyAL+7bxokNiYVP9UwG4TKD/fwnZoooF2HUiy4xRwORMNDBqDrSsP7LZN/o9N57CSODlyZeC0nkPt1ROehRpWYNvEDlLDG+04VgT9leTYIFU/4MEbpFFw0zA36TL0Tx+U2clj/WN51crBTweIBUh6pEwIgywY3IYCt5Yy4vxR0Qn3V4OivWMUo2KRAlARTtU5dX/UX81OYy7Dv8BFoi1CSayM4wC5cFHVHs3jXVvCvb5E/Hg==
    username: AgBSZRQBBgVcA8wfGYgE5iet7oXLkFfb+U6+WKeBt1I+lPImQ+jrrUnc0rd6bdULWS3mp296gOIR/d2JNuorPbLgdM6nFBF11AhiMwy0jb76PQY/wt3zkOmiqOH7zFBG/3i+BvAyWwNxh75jXZvLo+deNH1L7R5y195QthYhK8wRy93rmO+6mBBEWPB1958k5Mhcwsu6xGom5tYkfnddOTPSuzWtGjIhd+R2GrYlk92t2yPhnj2Ahc5QooSDo2ltkTMPwfWzWC0jB7cho0AJwFSTvSsL3uar+X3p00TAun5g8sud7LCZJdtbp1VWbIOX5hRJQ5RDdmrRKf10VUoTYE+LkNfSVMoE9HzUZGTFh+i+5RvtqhQUEIMfqEP5Rr3WBwfSyupjlo796r7MJ6NStW2K3QS6m/f8pPOPbzUoQ0qfpY3NbXUekCVGnF0QJMTYiROytMZyXhnvSVU5fygP710JIuqYUh++c3N4MeGRDiO5OOOceVj9TuNyjdEr5zx+g5OQ7250j0wzAU0eikaOqHjmBe7dedrAGNDGyu+jyBqYD6od2tHBCNLRj4Y8N361f6VTHoISTeBDqDghQAtrR5AJbT68X6pdF8wcExH7hBAamXQtEqq8KKr+6fAbMGBIo7feU3vnUj1OrGG8ngB+PVQeriMKq/+n+j+l88AkcER/clvMsvDE83ayvIDBlMIqlECRZIwyhehJGQ==
  template:
    metadata:
      name: endurain-role
      namespace: postgres-cluster
