---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-role
  namespace: postgres-cluster
spec:
  encryptedData:
    password: AgBapjIC0FEujlKTHM43paq+kldf957UrLu55ltONjmXGbNwtsG/41X4hduanwazj5JMgNSSUAgJyTXB/ijGktV+o2gKuxOeqTf7zbclTQ916mDaqHJXgBb4GJcHQWsz+rgOcvRPbBVbHX+O/D9q6EKRZQqLo3GCpVmw8LF4UUgGEGBRwcIHq1NGdm1n3rlzZVSQkF20ptb0sWGkAmpPM7febF4fcBSkATyiGcXnPLrhBjkC+QE/zFWquXkXBH/Bj+jaNFEuGgp/pY6Op/pheBrlfr+ZXtzUiVU4MDwcwZH0RKLLY/doTur8xZxNo4HPnY/+2nTj3oEaVADbKltp8x0NlhbAZa/g9fklbu6qGZvmnk18xAFeNt75wbJAGFax0DeBt4KFzvUPp+rDPoUbEvidXnxgMoiA4Ig5bYxvfMyUvrpVu+rSuiAU0VAeqFfBDX0xJuP/taKBXHlenqcS20z8N9EK9g9yjezWY9mzkMIwNp47SWFMh7cZejqpMNXjiYp7KXOk8zP9MLLzKspjIG5UTJ3Y/grI2fPwwVGdPYCZ88S17owrvNoYIrQqLxq+iGQy2CLiKXpVJODeSg5exqVROwZWGr1KMapDBub13iXdlRdxYW++6atfEYksmsLgYWYgLO/cU5okjExvKZJX5s7U2rVhYELaJ6wPCLdfgkTyBUCcD2ViadWmVQr58hsCOyztpjX4jA3lrJtVvuS5Xog76+Fm/zBJNHacrwRigAZF6MM=
    username: AgBAbBuaKbqGowLthSiph6KpzcphuUci2LnEQ5KN8jgWEOTowp4fLKfSUUjOfajXLBtWj4fqppzppxki/wDc0o8X8bWTTUBONrX1pW2I27UxwXAX/e/r9oUSZFlV9uL0zEryYqxtLMclzdzxmP4R5qhRLitQQJM5+2Lnz0aoIyTPn9JwY/p//r5bzN+uw3iMXIL+Rdi78kexDae0AoUqNtmvzycuFUtU32xHcD4o+KFev0W3G3hH6MRbW1iXo4bd42tcmWnyDRWgyHYoBrg6vPOGWYDils34LKJF7YkaJGqXj/kMYCWsgv4eXdY9oghw+6/VYt9xY9kA7waToqf1jtczlIOzZd1r9c7oYD1mSKh7vguY4ALuwcFx9yulR9YQUCXksuNf+rR5tevWCL+3zDYDrhok4HC8wh+5F/86ztQTbwKxntXJC2/9zMJ3QFFAdh4asbmnYP1rTWMIgAmeLgRtY95iBQ5pXPSY+6lB1DnPmiVxJHnwR4zLrxs97PqgVr8YZJIdd21lu/8TATktbPip4+EAQHS/SUDYkGsr5rsc+QkgURa0Fuvf6JtHeQ13hYIgavj4j0gMEaA3bfbw+PwpESws73siPUbYRuLYUeXboqcNpW8S1TpRI3rLyZRZyM0opP8kVVkuMd3SOAw0OlRPCQJTFJeyi+eSHYq49ZbjqCSkSi2uO1PzO7RW1qHPfwwdF+faVp0=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: gitea-role
      namespace: postgres-cluster
    type: kubernetes.io/basic-auth
