---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: romm-role
  namespace: postgres-cluster
spec:
  encryptedData:
    password: AgCbpDONAq3Zk8fnnZP3hHBN86iPaUOOJ1+w7C6crkAhnrYlr74D77+gEArY6cMmu+EL/xzdqW+GcUEnsLyRq/vjwtqsYv55Lr0Q9V59cJ/+kCwZutG0Bg4jGDQAUaQwjMuV/FnYe4nWy9k4Bv82v6CMRI651FN4wOUYbYb60QO8aTkHUvYSS1f9+QhnJ2s+QD7OR/k1OHKkFOLri7TGCZoIb+xu7jWlsPYtsufwODKP207TyKJ+UtaHi9QAKLxbQmM9/oCHpwKW1xeKAmzOpleH16kHdla3h6GprKLWsUNCOq0AJ6UWuPPorgyPxz5cFWxN2EdtjCrclqyBNSauY2CQ/gxEaFFnGYmjCcAEV9/teR+/IkeD4KOujLjzJ6ANxBxSC4KwT7rmsQJzkuMLtgEOFDRIZvghhJhKJx3K/ByiHRLZmsmMA55x315FfKhf3jfqO6y3F1hzfVETsF7S8zaQsCXMT7X80f9st5In9QmhskEbDR+ApJ9HNq5EvQ3DTcp418sLNyMizaa/LXK3NmSjqtV81DXPr+HFnMD5zj0OeMK9xpGgd7T42kfKazbiUy4R0+WBddhtU8cEe6IjgQFvDNvMw+C2R+EKlPdHd8MoDloY0FRWrLzLkvZijc5rXbh+hdFBXfTt3Xz9kCC/DHdpp90H1Jc+CCcQy6y4LR70iETgwi1ShjqmFCY1SZH+2KtKL2EmksqBb1uqpp8yCPWllW4p5LPmB/M=
    username: AgAfhr8G5PLVGa1FEHe/qwWK8NCAY3v+nzWzvBE1v1g2gmli0N/vqv8UxP/UhjNLWYFOueuPEl6h0KDzEg5uetPq/wVpW98ozAtRMp2zHZ1aIGhOimZrW/2EgTPejJhg3mRURDMbD9gDkAxH5XDKlpWXwSnii7ypm4DFD91r5s4n0daWtTD70HDmkWgJMDm21bbhxn1kpwIM5FrUDzDoAHFwzHdS8Hbv+9Isae+qNnf15Br3At72kHcs1Vm1AFAkqHcQF0CaRHzPfmwUr0nztqgYteYiTE6ph4oeTEKQ4ZawafiP+1T+JD/TNBJrCTfeGivqF5vZnN1rHLi8kDDxz1G0uAlUkStWEck6A9TDu+dejntOhBq0MTXISTCfk7l++jUFG07z4VooOFczkeR4zLqZxUjPcBXH9Z11cLoX2MxJs+RgJecdAzAGVAMFtq9+39YOf4P73Eeujmqi3fQOp/+7ndtRpMuxl1z3DwGtl97Dlh0WpYmFQ3bGv33mdK2QbVsOnEh7xnQbVml/GaW7fblfOmGGny0eFNoVhSit1WPFBdVG80F/lVqy5yiHrIFmcmvcz0jRyGwQH7pN6q9pIsvrG4sLKa22qP18XY7rj8L64lx6kP38P/v80JwAyNTG0bZniqvHwkYznDffzjH6RJh2nAfxpOVQfUf4pQ432W1TJXVEzu22/L93/OPwrvF0SIModnam
  template:
    metadata:
      name: romm-role
      namespace: postgres-cluster
