---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mealie-role
  namespace: postgres-cluster
spec:
  encryptedData:
    password: AgBUwFsw5mpbfDkTMn/xwD/meAHBGm5p3NNIrfYg9TI3cMwQ2rNRSaiqkXUaLmopKlPHqMdzd93JvwnVjRDAitW17OiVioLldvcKQNfau5ZmOd9mM2BSrZCx2m1GRmqpsPJxj48F22k4qPRJl8lMyv3xGwzdZUlxOl0ZICeBCXoB9fPUtys2GhHKw0crHlM9bH9so/mXOFWUH9ZvYmT2BfWCcvkXJm1rW3UzDrH+xnI33j1zhFU9bd33LX2L9ONR1/02qB+J3n5EpearPiWBwCqehS46p2l9CHe5Pi+7DdBWR0ecLVFH0kkEoQcRexyLAJSee+61ay2REnz1ep8PIG/TCLqufFTnSwW6n0SgMMisWin1F/8WsbDoY+w11D7twJtaT2q8PN6x/1z45ItsIaukctSDD3gcnpHFXI6wm8dg0BiDKbBsDwbWyarQt6WAKlj14c4tlY0iqa3MUFLOPLjW8C3Asj+RJiLENTnHj/8c6QmmNKIVhPstCICfb/No4gQT8dOwWuhiBegkUq4CYu8fn3tzptrZon6h8YHXgDyoT+sKMB5QpA3xGZYjdOteBZmrf1br9myZ353xA2xehnL6l3CHgQDnJCXUKiAL5wZlL64DfxMiHY7mzH+WbfDI+mQxCMME1Yy/WrzhbZMtHnDinKMWMqC2yGhngTh/s4l9Wr+p905ZkK58EerGW6w6nMwl01HwsrOSlThgXwnhXa5f6oEWTBJNT32c
    username: AgCDIskNgVw0ow624XX+MIuftuGyb9STSd5XiFIzzfIU8PFWDkjyjOIX5FoGemlKwdml3hHnIIh8/+UaVpi3vgkok74C8xMeYpeSimWH57UXfGz55+zMkNWc2CCIuBJEq24Gm5ebWXZL1WgK4YrELl5OR0VHQ03cRgStejirDq8YdsRtswvr4sWelFOFMARXRFvgDOoefXZP8xt9DI/e8fJJdb83Lalwmbzu6uv66bAlequEeIdCcBUQUveituOhbYgwpAejM+4bEapHvnfCQaadusMboAcnLrxEQDqCB/4rzPIHHdqsK213CzXOBN/rpmSp+IzmGrbqb1lxO5xE3mqooZMcRUAdhs/386Lf5trfSzxGJBGy4+1InNFMEZgrLf7V/R2+vDRndiuWkXhsYxkZMSDHJdeJJp6zHmEyuQ6GYgumCfrbqn1q7p4cyc+qer7/GTQfg86LePLzwhjRhL8ITxR1ujsMW21EIlZLsjrlW3eV1XeLDVcZ28YC817f3PEO47ql7OfuR/TOlYHuaNzgKw8c/z//aJKxQA203O5NE5RYMAVAy2WimpV+S6BJm1/0BtOFRZGF/iKe9FY1NFcRS2DMWeulHR+Ro9i3J/iylEW0Xhlth8BhRlCKP/lbsCu0R6/Let3DWtdoMgO8h6vvgnS5QU6+uUq3aBWgl5LBUFVLrSWkEFgEhD3Vi8VViqeaczzZGUFn
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: mealie-role
      namespace: postgres-cluster
    type: kubernetes.io/basic-auth
