---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-role
  namespace: postgres-cluster
spec:
  encryptedData:
    password: AgAM4D30t/e2Nrz7DK2RyI+GzX6q5TfNoytuW5LVeuKYo3L+uYsuLlZh4GJgunxR9jMYrOGaoH8/y4kUhFDVyhcAyjqshHnEa+iiIJ6GmRcMgdfp+tZpGV+ykFanrP+baZL/bL0RXoACj90NT2QmMbn9ZnMyb8B/VFfJay/neiyt5rnW04kAgfm6SExDTfqJfzNOGf3YII/QK63P0xGPgtrQ5DFNta6ZxEbojPNqQvx1t5jyWfGM5RYW6r0tBw864+lJh+Sofs/Po/pbHU+GNisqDA3jo6dyyNGpWeDMD7OwF7+4fXd5KH4KZP9xDcdS4gv5hrt0ydjagIN12E9IPIiX0mTNrIXduNVgYm3IydZj5fRcQHX3Pp9YwEI4rdQdzO7Awq7q+nVtBcBnjfK0//5/9L5GkDfCgdeyzNzwaH2gSsVB9hAPz8tXfj40Y5t/w4AdQoz7dPPlF59hz1UQvFpFhX+mxWOkzlp1/Mk0E5OKqTEG4CPgen50SN6FXLjjpjJFLhObzUi+M3EPHOr+jsrszBn5acXMu0tOc3+djghumaa1FAWPnV/Wfj7HldbXO4vyYjmsD27CdigpkgYemokAoDPOd5mGXi/5UTTSEFAf/X3UvdZWKaVZRAYs6xpGVuv/g1osfr+tA52aKiIf+2c6OEAzv0y+LS06P4bTJf42QjktwGbg8llYooHJWagDGp7Htmuyt3fZ/jYdB/gB+B+h4Q==
    username: AgByw4TiHpKsw+XctH5h4qjs0MVRPZVdFkKwTkFzuYXByW3Kul9x6gGS5ixpL4VDWttWAEB42CfOOvlL+OTWeujNdceRon9zeH21kX+mmiprYc2bC9fIAjUUlY4lYc+2lSRV+T9daLyetF3KPdTl//JoVVNJ6vC8/bYA4o46wLv61J6lhwZM7N06jKD519Hunl3y/yv+CdMSi5eELBcvnmyLbi3CxNY6FPTlg7twju3WtUefkeIEaqpijJmPaxNJ/gBHfpJ0STpRY+EQ2sMDI64qxjvzqac5ItVyTXl8c9+4n+1T+I2Hj/cwjbHPi6ut9vGjBko5sLdfehvSteq6HvRVzY51Io9h/x9hzOZyD5m8Hrf50EQ1TkSofMugqeavrbU9nJpJZAncjO4NY/U9cumuMiHdylltMCTanQkvKUHlMVnr746PTAnHJJ8Ens5aoDbplWO0yYxyaBZC177MsuZ+VyL05y9F2awLo67Ik9qcS8sEn6yQADuXySz8Dc9QI1VHkkQLQa00NiP/UmnPcRlGnU6QgXedsQYDRId4aoCB+MTU3xS60W72SoKsuLC9hHbuD0W3CaI0FVDJgjrCzyhsDosoSnLA6iLWurW2PhEjzgRSt+5Mz85y1SeFTO8ktJCPsW9w18Hi+DDHvlpVAursr5Eb1CYM1DnnUaZ9u5QUUkaT/lycTLCwv3ITi/QiwWkkvCSIZBvFu2tWwdA=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: vaultwarden-role
      namespace: postgres-cluster
    type: kubernetes.io/basic-auth
