---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: endurain-role
  namespace: postgres-cluster
spec:
  encryptedData:
    password: AgAy4R3QcUC3wQNTes+0E36L/Q76mqcOecsdNOX20DDr/RBXankCZ2rM+QZIhwAz0bF1bsfblRH2D0tu9fvQUYHJ8VAQ/K4exVYNMtFh8hwrSX7fOFbsRnyVJU9FL3xhpvNCVsQAxQInNQJDcJkVpk4/VXbeEruO30AQNjFlkUlEWtwd/bW7ciUy3RasK0YwUNjF1NBq6IktXZEC/vnYFse7/rmZR8qAZfw1Za1PMjs+8b5w4d/g121kM7Jx8bqUhDaEcLddXos1n2HSYnNolKPqwCyUGPhcybtVnlqEsB6lyqdoGpV29wPuD2gB7UoD47lzq9FWky/2LbKtbh8NdAArPqxEd6a0tJ94CpD3r3HZyLCai/e7kxmbHf53suY77dC4WKZQgT5thBySUmNdFKk+YUDuRmA4WU9Gv48Y97x8ub3jESCrg3aEEHI+asebb44mIcbSbRzRIOBo0p21+LEY0en4R1Y9ijC7vO4rCp6+gHL5EcX9mUjCeLTktRGbGxNbtKXlD4m2gls0l/6EoOvl79ww/N07ohotA5PEBkGfT62eWL8ECBDMSlWjYA76WNRhhhP5moQ18xuib6Pa5RuygE3IUapj0vWeT68Sy56az675R/43JD7cf6R+o29hTysTQXQbTkTeE8gfn2jte99gHozIKBbkgeh/wpNEEOUPsI3aO1sSUwtGFyMU3+g9mLo/bsdUw2KKHu62KdZhev4fl1IadZgo9lC94WyOVcPnbQ==
    username: AgCOsUgV+qwpqI56XLbRypDhiNh897nJ6vw8oIlGLsg0nEZNXdInTh58vUxktOSaIhY0t7ETFuB3OkA9NkDD96sUmOM1VYzBQOwKEin5ynf9o0lnl73rNdNmobOambCJXXatGtd5I+JikEKPZLPa5BSmZgO8p/qrVPTJdeC4gdQGMSzlYr+scyNDQvgQdJOWmAogIoYuFpYuuCpk2Ntfr4yHtEtVIHvr4PVpuv3yYKVhtYUVg8nEWFbB5FkS1DMJsR/pLmGqXzXvcQ6Ktg7coqGruO3TCV17fra5o17cwbRt7RYTOwVFbdTKyrybm3eJ4W3zSyKET1d1nuJrVXv7sRGr0cdV8y+95foB0LJgGgBwXESZsv7puJwg5M2ekRibnWhvOan4ndjDI+nr1wv7anIRcE7+W/bBdN8F75WXWv45KxoEl6pyVJxBU4MCwO+Kyrnpu0dyKEqzoXR7HGkz7PJAtCWWqcIuPZk7b1esaqplLuQ0tl8hpkLpyZ7s7Y7J2hz3OQ0ooITYbdgthuq3km9A8W8pRLJCpmWu4c4ob91+FnYkvhRfLLfQaq388b3diyE0JmDHxN+ld4MOpNUo+bD5fqIxsn9kSaffQbkgJKyQdt5Y6rIx8xUv/hLzjMEXzQ/clVEUCIbGwi/6iNdasbqMFN9jUYox2PKCcNgyP/ieMXbbbcnvZyw8LADmrF8ks9kO4kpuuWapPw==
  template:
    metadata:
      name: endurain-role
      namespace: postgres-cluster
