---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-role
  namespace: postgres-cluster
spec:
  encryptedData:
    password: AgDLt9I3yrb1yZSsHjdZDIOBEbAruJhuPVPmiXX464C3qfxzVy/AS/EzZn//bRSV+P2IYP7HhE4SWb6I5Y57aEV1dIL0wJ4UGPMTx1MsxEAEsMPsDvcAHvgmDS3j2cVLYYIAG9tt5Iln0ftS+i/CneoHIw+4ZGsrWbVB1/JQc6WQ6wqDnHsMPKlFHR20pHurPskAOJBL/mmzpQDyefps6jgYFTcPh/Z520M6E+89NVSoVPEseEKIHKIpMBSnAKj+2T1alRPhlmZxS04LV41r1EsWrnl0AdmLMDCDYB5/W0XCDjvBMt5YhfpTBqRMj/wGiPO0ka+lATKVazYVseftwJt1bxy1ibk51igOfvzsxWdlvIMHPE6iaHwhFfJzYfLOn3mM2tSZeT3/r2i36jIpHSSo6n7QX05370ETKgzaIN6fzaSIIjaNgc1kkAZKGDDutXWBSj7M43LwIwFlC2/jaLFuHGfHjF2Tzpn1Gt4CucymrPy8axilSlmNy+scAhM5VIZQtBL90YqYw1F1rcGeZlgEOCn/J7EXdYflGPi9o8ZDVB6iOLin/Pkm5dhXruhela9Cn7+Xb7u/rdK6Qz41x7/zdcpZk8qb7Q1AuOw8oh9jxkOG2ujWdGBzKMOOAvJrrhqguQ0L7ar6zK/Me7R8MpFswdpJ9cqZMbv8FxLF2udI7uYK+jbZIHwr/MZqfiJ2vgvzRsGWWK7egl/zLCz337FX4+9zzoYG3JXG
    username: AgDQWnJhlw7BIIr+ztVMw6i5TJJEZyoWBLt1T8fu8LzEymRJh/gYp2x00m9Z9q3WzJEGXjQWoDgTKrlvLeSjJuh4zvnFHO9iXNAmqn12ZAxQO4yYeqvb4C0UGyRNl4IS7QeKWEk8/ZZLjdiRJrtTjiJ2tOzYmhs2jPDRhAQOeGX8QgkF9ZwBXZsMrJFL9ysgW7PjkIAv+7gIuJj0iyi8h+46xbnVs5lLsQEHzTAPhQdaT0uvVNfZiZ3N/Tl2rbIsegVrylG+wDIGYO0t9LfCeKu+P7hnia+jO2myS+06yHYDeVk9/C9he5PUVUqvB6lUj9q+suN/XALhKJjdZmDkvKkj4ixZflxu97gcADrUvtNP4MeXSllhHjiWsLCgG5dapqmeFWLeE6+0SB8lmk4n07GBAWjwZCw9qIj76L+LBa2+G/PGbRg1fM6fMMUiOpRXhu73rU7r4L3A8BPxn/0D9ShpbKlcEj1i3PtZczHLp9LIgM2LLnPBAl4TTKcVI83aoxIZ9gLXzhA6t255PAK4rPQ7Ws0kvWnsCPhuGEJEcpMPeavZP7iUGR327D5bisJq4eevlYAY+j153mqKnBNNWLBIklmpYoP03Vb0/eMXGdqDwxJX+tDLeHbtGYDyJ4V9hURn5mDB3j6tHusoKllPAgb5kS7BYKZSMFFrJxRQYx5MK0RcNw0oBRlXaQuVnH8AUdjbQICh5kdgNjxj
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: authentik-role
      namespace: postgres-cluster
    type: kubernetes.io/basic-auth
