---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wger-role
  namespace: postgres-cluster
spec:
  encryptedData:
    password: AgCsL9gE967BRPPGCZODNLNaIW9I0sriVjkrwDzxv28ByWnvDJndpTJ/ccBnc1isbgWqUh1u59PZwQMb1fKN5v+0WES/GT/zByIGMepeY2bOQ+Anltl4zjldu4U5wT/syIIWx/gmwwqI0RYULSjuX9+Tdq/D5shvXpTtUOeX2dWhMUWGFXgjWTWtgDH2K6ESUeAocLC8WoIdknouxvomy5OR8VSdyrm/ylxqJSpnJ3eMWKw73InlY6pllkqxs47cq0hXV6MLuC2UlmXRYhHmkAfE0BzS8JIRWKfVeYVincMe8gc/OAoWBhwYqVJcBNrouNFYM1dUhsq9VgExPbEhv5kcdzvbWmrSG4bYe4KTLtTHPMuwIjay7B6vDsC0lYbU9VjmMKla8R75S8t/1WmCy7KoyEEluV2hL57auNgqQtAvHcxqr6VNqkW8n3GNFyRE9xosGbWin/ABzaV3bZ62kc4+zrTtYafNIX4GjIszDcEOul7bfEqeot0wLB1BJ4/eAmhB+O7BC+oSF4dGEDN+bjnyjyhj8cj05G1K4skpMtxhHFrayxsuuSkD/9D/k1cTvsomo6BlvnIZ3CQfnWbmzf/46lcMChYcPwFnv1ZWfbx9P/Txrd/20XdlLVebUcPdC59iXTXvf5eokDGdxtBTyIEX6rH0vjuHJa+e+t05AQTGzZWUZnPRaYTHTBIfambTv/5BGOhl6OL8vnsvKhX6yP2v8WrHvmO1rkt0VzXMAdxLf0w=
    username: AgCWfcaRRHmjrcpHz3ek3TLAmTyKene2+WTS7FlnfFhsjr3cKVtLON5YCJcoNU7SDNeTx8eckBLQHQyi1ARpSu2KvPzSH4rhMZh08bpSk67G2kydKzjwHcqvBg6KiRp4kQ9DP+nBuYvbpt332XyTRA1xz5d0WaHIYt5FGSPL6merit+R7Psfd6igOrefVHUP6INtxKzH+jvnzlXHFDtz2fY0Uz98QPzNKq74Ji36KZIpq1hmE8mChpYQXGBklBZSSihnJ3er+Vzom0HRwrDd3uB9MJx+l98NbrTF+xXxQWJrZIXoljuGo2p5/+ZvH5ZooGDHCV6asGVUYXTZJl/pG56pgADvqTnsnCwbCncJWcnxAazjGjOi+7ct8R/c1AjdtfurQtXx1SGMWlCPIx1EbD7GLo2D4tiTPHZCn67bPODzWStmRe5Dzj+nlkB4lLH4o9T0NlGcrD0VnUz2uyfLBaTE1UelhdY5QOZKLLUK7iRmIRM/0vFB2eIQi0nqnMLN7jbWQiqKkraDhXaJ52DEsVHrhpwhLx6tYgVYgEjV8mAgiwGWeUNGDEO52WdSsmY8qPP8qM7PgKgJq1pYM6vr8zjVQs+HpMbC/Q36rgkxatsaWvYTNit2/S1e1VI1apnr0NeUBgcLNYNhC+Aa2+hLThedX8c8nPnWhCVMn2XN18E0ovb+LLm3q+nP/7uExPZ231S7ppmkLg==
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: wger-role
      namespace: postgres-cluster
    type: kubernetes.io/basic-auth
