---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr
  namespace: torrenting
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prowlarr.47fc5c.com`)
      kind: Rule
      middleware:
        - namespace: torrenting
          name: prowlarr-ipallowlist
      services:
        - name: prowlarr
          kind: Service
          port: 9696
          scheme: http
          sticky:
            cookie:
              httpOnly: true
              secure: true
              sameSite: none
  tls:
    secretName: prowlarr-certificate
