---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prowlarr
  namespace: torrenting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
        access-postgres: "true"
    spec:
      containers:
        - name: prowlarr
          image: docker.io/linuxserver/prowlarr:2.5.2@sha256:2f3d31307beba3ba2dd226d191f5f5c14ee3b4d8b49277c64683f5ed97083179
          volumeMounts:
            - name: prowlarr
              mountPath: /config
          envFrom:
            - configMapRef:
                name: prowlarr
      volumes:
        - name: prowlarr
          persistentVolumeClaim:
            claimName: prowlarr
