---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr
  namespace: torrenting
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-crypto-global
  resources:
    requests:
      storage: 500Mi
