---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
  namespace: linkding
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      containers:
        - name: linkding
          image: docker.io/sissbruecker/linkding:1.46.2@sha256:0c0a9a04c7ebd644293c37f98710872fe7cdff0ea1ff7fd9be4d235e4c4678d2
          startupProbe:
            httpGet:
              path: /health
              port: 9090
            periodSeconds: 60
            failureThreshold: 10
          resources:
            requests:
              cpu: 1m
              memory: 160Mi
            limits:
              cpu: 25m
              memory: 256Mi
          ports:
           - containerPort: 9090
          volumeMounts:
            - name: linkding
              mountPath: /etc/linkding/data
          envFrom:
            - configMapRef:
                name: linkding
            - secretRef:
                name: linkding
      volumes:
        - name: linkding
          persistentVolumeClaim:
            claimName: linkding
