---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding
  namespace: linkding
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-crypto-global
  resources:
    requests:
      storage: 100Mi
