---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  sources:
    - repoURL: https://gitea.47fc5c.com/fraccs/homelab.git
      targetRevision: HEAD
      path: kubernetes/k3s-01/workloads/kube-prometheus-stack
    - repoURL: https://gitea.47fc5c.com/fraccs/homelab.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://prometheus-community.github.io/helm-charts/
      chart: kube-prometheus-stack
      targetRevision: 70.10.0
      helm:
        valueFiles:
          - $values/kubernetes/k3s-01/workloads/kube-prometheus-stack/values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
