---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lidarr
  namespace: torrenting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
        access-postgres: "true"
    spec:
      containers:
        - name: lidarr
          image: docker.io/linuxserver/lidarr:2.14.5@sha256:5661b79d7245ec0c196a5a35ac13be44c6d76563d9e5bf855b3ffa3b91160999
          volumeMounts:
            - name: lidarr-config
              mountPath: /config
            - name: lidarr-downloads
              mountPath: /downloads
            - name: lidarr-music
              mountPath: /music
          envFrom:
            - configMapRef:
                name: lidarr
      volumes:
        - name: lidarr-config
          persistentVolumeClaim:
            claimName: lidarr-config
        - name: lidarr-downloads
          persistentVolumeClaim:
            claimName: lidarr-downloads
        - name: lidarr-music
          persistentVolumeClaim:
            claimName: lidarr-music
