---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: owntracks-frontend
  namespace: owntracks
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`owntracks.47fc5c.com`)
      kind: Rule
      middlewares:
        - namespace: owntracks
          name: owntracks-frontend-ipallowlist
      services:
        - name: owntracks-frontend
          kind: Service
          port: 80
          scheme: http
  tls:
    secretName: owntracks-certificate
