---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich
  namespace: immich
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`immich.47fc5c.com`)
      kind: Rule
      middlewares:
        - namespace: immich
          name: immich-ipallowlist
      services:
        - name: immich-server
          kind: Service
          port: 2283
          scheme: http
          sticky:
            cookie:
              httpOnly: true
              secure: true
              sameSite: none
  tls:
    secretName: immich-certificate
