---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-machine-learning-cache-encrypted
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-crypto-global
  resources:
    requests:
      storage: 2Gi
