---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-server
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-crypto-global
  resources:
    requests:
      storage: 64Gi
