---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-server-data
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 36Gi
