---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-postgres-vectorchord
  namespace: immich
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAX4HS6050nWm3KFv/3gBF+36CPQmNyO5W6rGhpKgzyuAGAS5TrDQSBTZ3m4979Bf66HDerx8zLrFvzCGsPP0LBT5cMp/vTyTNXQ7gyHSQgjrg1b3Tt6lpiu6Pu5x9xFMBXfhmf3UbT84Znb+fUHNp32ZZMcbBHZ6kNhFg2zwbCqwT4e+G2zYsTw6FtYT79HXb8s+aoFcP211dKqggC0ZvMTuQJoPIw6ro0onxESf4RRjXsAfwou2gEAAxP39QYI8DfDbTzM4YhT5zjSiehJLKXab4S6GO0r0eh8ZrXoE2piG0DlmBaLcTkxcZyDsBjYfraVFICvjyeSYoQTfXUPvZ+Q6r95p0Y/6gKAxDvoHsoY14cyVOSs/OtjLSgYGsaoX8EKShkR3R+EwEAx/wlWgoVurkjaYma36puFs1A0g2YjToY+/NrBXmmyBfzkdg72fk1oLTnGGVjYX/uf9YbFx4rHPBc70dhNMvI5w7IflK9+5iABO+iD2Jrf+1v5tUpsTUXRZurbi0jH7Jzb4ryvOGKGN4YFRQt2kjLrGw9hy9mhGJ3VkRi4OYHwHo1jyqEwPssS+iYhpVDdLnR80nD4ggiQnmySWnOaZRbNfnbrChoP50T9bs/S0wn64J30uvAJNODB1HR/KdpnYuH9Pw0Qgy3PQ60zjAJaYmV7c/tsxvtdRr9mKciMKb8CoaLlzj6glmcTdNUfRJBjsmTsNQGAXgXYWUWbVLM7QE=
  template:
    metadata:
      name: immich-postgres-vectorchord
      namespace: immich
