---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immich-server
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-server
  template:
    metadata:
      labels:
        app: immich-server
    spec:
      containers:
        - name: immich-server
          image: ghcr.io/immich-app/immich-server:v2.3.1@sha256:f8d06a32b1b2a81053d78e40bf8e35236b9faefb5c3903ce9ca8712c9ed78445
          volumeMounts:
            - name: immich-server-data
              mountPath: /usr/src/app/upload
            - name: immich-gallery
              mountPath: /usr/src/app/upload/library
          envFrom:
            - configMapRef:
                name: immich-server
            - secretRef:
                name: immich-server
      volumes:
        - name: immich-server-data
          persistentVolumeClaim:
            claimName: immich-server-data
        - name: immich-gallery
          persistentVolumeClaim:
            claimName: immich-gallery
