---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immich-pgvectors
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-pgvectors
  template:
    metadata:
      labels:
        app: immich-pgvectors
    spec:
      containers:
        - name: immich-pgvectors
          image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: immich-pgvectors-data
              mountPath: /var/lib/postgresql/data
          envFrom:
            - configMapRef:
                name: immich-pgvectors
            - secretRef:
                name: immich-pgvectors
      volumes:
        - name: immich-pgvectors-data
          persistentVolumeClaim:
            claimName: immich-pgvectors-data
