---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immich-machine-learning
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-machine-learning
  template:
    metadata:
      labels:
        app: immich-machine-learning
    spec:
      containers:
        - name: immich-machine-learning
          image: ghcr.io/immich-app/immich-machine-learning:v3.2.4@sha256:e16c2f166a8174901959fdf85e2e4c7bd1ebc4b37e0b6655de97c41408a260c4
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1024Mi
          ports:
            - containerPort: 3003
          volumeMounts:
            - name: immich-machine-learning-cache
              mountPath: /cache
      volumes:
        - name: immich-machine-learning-cache
          persistentVolumeClaim:
            claimName: immich-machine-learning-cache
