---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immich-server
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-server
  template:
    metadata:
      labels:
        app: immich-server
    spec:
      containers:
        - name: immich-server
          image: ghcr.io/immich-app/immich-server:v2.7.5@sha256:c15bff75068effb03f4355997d03dc7e0fc58720c2b54ad6f7f10d1bc57efaa5
          resources:
            requests:
              cpu: 50m
              memory: 768Mi
            limits:
              cpu: 200m
              memory: 1024Mi
          volumeMounts:
            - name: immich-server-data
              mountPath: /usr/src/app/upload
            - name: immich-gallery
              mountPath: /usr/src/app/upload/library
          envFrom:
            - configMapRef:
                name: immich-server
            - secretRef:
                name: immich-server
      volumes:
        - name: immich-server-data
          persistentVolumeClaim:
            claimName: immich-server-data
        - name: immich-gallery
          persistentVolumeClaim:
            claimName: immich-gallery
