---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie
  namespace: mealie
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-crypto-global
  resources:
    requests:
      storage: 500Mi
