---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-encrypted
  namespace: mariadb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-crypto-global
  resources:
    requests:
      storage: 1Gi
