---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: docker.io/library/mariadb:11.8.9@sha256:2d2f4095530294735a857cfe22bb101e19b0849b416911c796ec4aa81b164a62
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: mariadb
              mountPath: /var/lib/mysql
          envFrom:
            - secretRef:
                name: mariadb
      volumes:
        - name: mariadb
          persistentVolumeClaim:
            claimName: mariadb-encrypted
