---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: docker.io/library/mariadb:11.8.6@sha256:f5644a292224cdf4b6514aca38b3b4436f0b0443d54170a472cd14261f31402d
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: mariadb
              mountPath: /var/lib/mysql
          envFrom:
            - secretRef:
                name: mariadb
      volumes:
        - name: mariadb
          persistentVolumeClaim:
            claimName: mariadb
