---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: docker.io/library/mariadb:11.8.9@sha256:2439dcd7d14010ecd1ff7a4e1c5abe8e208c34fe35290744deeeaac3569043c3
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: mariadb
              mountPath: /var/lib/mysql
          envFrom:
            - secretRef:
                name: mariadb
      volumes:
        - name: mariadb
          persistentVolumeClaim:
            claimName: mariadb-encrypted
