---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: freshrss
  namespace: freshrss
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`freshrss.47fc5c.com`)
      kind: Rule
      middlewares:
        - namespace: freshrss
          name: freshrss-ipallowlist
      services:
        - name: freshrss
          kind: Service
          port: 80
          scheme: http
          sticky:
            cookie:
              httpOnly: true
              secure: true
              sameSite: none
  tls:
    secretName: freshrss-certificate
