---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: freshrss
  namespace: freshrss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freshrss
  template:
    metadata:
      labels:
        app: freshrss
    spec:
      containers:
        - name: freshrss
          image: docker.io/freshrss/freshrss:1.29.1@sha256:ab6b363102ccdbc39f6a62db926f567c61a5289bf25ba460f1c34423d8cc1a4d
          ports:
            - containerPort: 80
          volumeMounts:
            - name: freshrss-data
              mountPath: /var/www/FreshRSS/data
            - name: freshrss-extensions
              mountPath: /var/www/FreshRSS/extensions
          envFrom:
            - configMapRef:
                name: freshrss
      volumes:
        - name: freshrss-data
          persistentVolumeClaim:
            claimName: freshrss-data
        - name: freshrss-extensions
          persistentVolumeClaim:
            claimName: freshrss-extensions
