---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-vip
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    repoURL: https://gitea.47fc5c.com/fraccs/infrastructure.git
    targetRevision: HEAD
    path: kubernetes/k3s-01/workloads/kube-vip
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
