---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pihole
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: docker.io/pihole/pihole:2025.07.1@sha256:f84c1654bfbafc44e2ac8447a1fa2fb739eae66395b4c179d2c59cb93e1321f3
          # startupProbe:
          #   httpGet:
          #     path: /admin/api.php?status
          #     port: 80
          #   failureThreshold: 5
          #   periodSeconds: 20
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 53
              protocol: UDP
          volumeMounts:
            - name: pihole
              mountPath: /etc/pihole
              subPath: etc-pihole/
            - name: pihole
              mountPath: /etc/dnsmasq.d
              subPath: etc-dnsmasq.d/
          envFrom:
            - configMapRef:
                name: pihole
      volumes:
        - name: pihole
          persistentVolumeClaim:
            claimName: pihole
