---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: docker.io/library/nextcloud:34.0.1@sha256:6444fc5450302534e850b4d23c05b5f06c7b0d25bd5ece716452061454699c58
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 384Mi
          ports:
            - name: web
              containerPort: 80
          volumeMounts:
            - name: nextcloud
              mountPath: /var/www/html
          envFrom:
            - configMapRef:
                name: nextcloud
            - secretRef:
                name: nextcloud
      volumes:
        - name: nextcloud
          persistentVolumeClaim:
            claimName: nextcloud
