---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: docker.io/library/nextcloud:33.0.7@sha256:2e0ba719164b092fe0629c6e36d154e39155403afaef895116bcc37e88a52f09
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 384Mi
          ports:
            - name: web
              containerPort: 80
          volumeMounts:
            - name: nextcloud
              mountPath: /var/www/html
          envFrom:
            - configMapRef:
                name: nextcloud
            - secretRef:
                name: nextcloud
      volumes:
        - name: nextcloud
          persistentVolumeClaim:
            claimName: nextcloud
