---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: musicassistant
  namespace: musicassistant
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`musicassistant.47fc5c.com`)
      kind: Rule
      # middlewares:
      #   - namespace: musicassistant
      #     name: musicassistant-ipallowlist
      services:
        - name: musicassistant
          kind: Service
          port: 8095
          scheme: http
  tls:
    secretName: musicassistant-certificate
