---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: musicassistant
  namespace: musicassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: musicassistant
  template:
    metadata:
      labels:
        app: musicassistant
    spec:
      containers:
        - name: musicassistant
          image: ghcr.io/music-assistant/server:2.10.2@sha256:09c02b4ee491976efa6d698265f72571f064031bb1a2c9a1c32e104392209690
          volumeMounts:
            - name: musicassistant
              mountPath: /data
      volumes:
        - name: musicassistant
          persistentVolumeClaim:
            claimName: musicassistant
