---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: musicassistant
  namespace: musicassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: musicassistant
  template:
    metadata:
      labels:
        app: musicassistant
    spec:
      containers:
        - name: musicassistant
          image: ghcr.io/music-assistant/server:2.8.5@sha256:fb0ea93078c747d327f86a832d6e11aa2e47dafa6009cf0d4aee5bab60db19c4
          volumeMounts:
            - name: musicassistant
              mountPath: /data
      volumes:
        - name: musicassistant
          persistentVolumeClaim:
            claimName: musicassistant
