---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: renovate
data:
  config.json: |-
    {
      "dependencyDashboard": true,
      "extends": [
        ":prConcurrentLimitNone",
        ":prHourlyLimitNone",
        ":semanticCommitTypeAll(bump)",
        ":semanticCommitScopeDisabled"
      ],
      "argocd": {
        "fileMatch": ["kubernetes/.+\\.yml$"]
      },
      "kubernetes": {
        "fileMatch": ["kubernetes/.+\\.yml$"]
      },
      "major": {
        "dependencyDashboardApproval": true
      },
      "packageRules": [{
        "matchUpdateTypes": ["digest"],
        "enabled": false
      }],
      "repositories": ["fraccs/homelab"]
    }
