---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-bot
  namespace: renovate
spec:
  schedule: "@daily"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: renovate
        spec:
          restartPolicy: Never
          containers:
            - name: renovate-bot
              image: docker.io/renovate/renovate:44.5.3@sha256:0de2072bc4c87e1744158adfb8ccd9f49c5bd2da5a0c14bc4b0c90a7cdaab54f
              envFrom:
                - configMapRef:
                    name: renovate-env
                - secretRef:
                    name: renovate
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/
                - name: work-volume
                  mountPath: /tmp/renovate/
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
            - name: work-volume
              emptyDir: {}
