---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_GITHUB_COM_TOKEN: AgDHS382RsmTEO5OpdBFMI98YBCZncMsTNgcdoxm+Qaoq3YUVNE2ZJIHdEM4lAdzpWKEdZS/wD6YKm/k/HIuNHPPCojjI/D7K2tOXvPQQGAShUUheLHSnZgbe56J6n6vdQ7IErZOyTGDjCejzsQSJjOUF9/OxtxOMXqnH8U7lgAN4MiKvcEpxF2pUcnJmOo9lQ1AQK9dNHokMULm705B06bdiSX3y7zYGZavlGWBE0qwFQyhMr/f7j4ypgDMijr+qcLrplq17th31KBvOgLzdfIi5v4Hkjdt4kNNRXiCHibdn09KSJJoYFwl7ENCMfVCSXD1F/l2UhmXwGfbq7/Zc4bfb6qb1T+nLrp6ts+WY6H182b2j4Oxz9wCzL4BYhBj0ywj0qTAs8funILl7qeZdJz/Ntj1ugMsP9c+SSc10mf4o/wnCmSi8COmk0MirlutPJ9sABduGrzw3K8HAmx0lpyxWUG233MPAkMQoJc4zbG6/JIO8ys8n5Ymis/xsmMtIGcCkJMOjKsYFp1o+oFJ0rQJQWzAi49QrVpa456Ct6aWUnDX1EJiICRJASyzfZCpe60A6C4Ikrucn2NttdIn0qtXbRASi6WmfyVyyUEhAli/9gkAQN8VcDTSc1+9grXXeiSc5n1srxYjCTbIfdKME8U3wxGMCuaXk7yffrCypcTKV5aJvyKTv1QVCI1moy5B/215uCuv7hN2udgNvImY6cP9d9eULzzA49UHaGbJRqTRN3ci0GVdwRqkaw==
    RENOVATE_TOKEN: AgAOjHkK1jI+DMvttWXEraUqK2mnR0OUyd+WbGfDvQeA0Moa6+aCfJilqUXqZNVMHrze6+JQh0xaPKNtODIIgiZ5Qzr2jOYsWXY67G46LsrOEsZXAHlgteYkPgyBPV4wGz5OvSDeh3NeKLHE51IewpAHiCm300+IBjJW/Og0QohN6nGmWu6qUwX6KCXLaEcfX7kCmdWt9KqrAyWKSnaxUBwTF/RQdeHZ+ltgdK9HpESDQ2OXrpw6H1iHdVc3Rc99TsNPOfD6hTBgExteD20z5DePXhOcYKXEbyBuAeL1Ws/vFRTijoU9f9asIzqY2t5GAPQVpgmoVK3E//QKFeylxLy5W95uCoQtrwG/XlNZBOM3Rw4GfVQ9byJBhysYnfqA7AeXNHt6U3TANrlaOGMtme25qgFj0zFiINqsxpxA7h3wMOlr/sEJxmPQGA7CNmvN2FyWIaYjqMKaN13TMmycm2xSrw3tiweWXscQTVbo7x3mYTxVijQa1bXbxzpxBpqsnclB2FigF/xGwnXfxvJ5Zas4tiIwmCw3H90jofwLFf6gFVGFSUukdpfp1y97lBfdFk0BpneH7xbjhC15ELKbZLZDfubJLfsiBLbMaF7ua2p8/CU+Jj0Kb8CBnuKWf7pYNtet7+yZS8jY/CanZKVWrajTpUI37NrBKd6VHzU9ekFq3Wg96x4QvAq1ukLVf+8v+ohXxR2ZoE8ggA4BxOcGLNY2e00rgPCN85dMQoJGtN3K/I72n0R0DU61
  template:
    metadata:
      name: renovate
      namespace: renovate
