---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate
  namespace: renovate
spec:
  encryptedData:
    GITHUB_COM_TOKEN: AgDCvsgXsMzlF2LMyqiw/tKSxGGebfoWfVONfS/xRM4ATM/6la/W5S1GRrmfHytGBjWX5JHbUWDGOVuKE/X2sDAUxx6jyo7vCig9a4MuCKucvRboTgYHo97rRrN/LfVwfm/++m960HsifIqJtf5TLgq/tAqEA7W/F9ifiCJEucNVsIGNyOMhPuUyu7a0UIMtuFZDXp3/WyLbzwPNK5CuIHN1I3cFNOEf7kvQPyhLNQck/omTamzr/lppg3XhX9/oUr88rKPyEjAFXBSEAeviKtsLHMqFeLnIlXy6ZDzmeOJ/DlCnn+2b6Sz5BAvbbrcG7d/jhuQsF3Dr6RxxYTOeNgvRu4K0oUV8dnCHebr11mByf62Nyds4WJHRoejRfGpRrSohrf/PLSuFljAJEmbUySLynXgQ1NT8WwRSiWloyHCAtzU4DX0MwJO3kql68W/48Lz70N5mQPLWLDskwn+Sp9QGdRDDSBN232XQGCNcAy3Syw/MjSigxtFgg52QDj1MjVvb0o/HKOGmdP9HSrv9aCOaH04NZWWACE9BBGX+rlwyhirHoXzdpeacop5IJgv4wfRKrCTkAnjBh+45lIZ7M/RKtPD0q+uif/3CmVilFcxHhbUg4IGKrR1lEsopPJMBqoLILxWA+Nn9tIptDK38E+re+PtJNCROMf/K8SgawbNLFbuHRUaOb81X1qD6eg44WDkascBrS0+ZhK/y3oUmRwmppDcBF/6CztYfrBWyXxgrLKbU4Ec97tOs
    RENOVATE_TOKEN: AgAPAGKbONmMM9lpBoRyFu7mAphwIBohg1GljviKcSZQoGhqduuIs1Hhlq0ZLRmPZiq3AhO337UbZlzJNmBHzimY7m1+pNAU3ZACBd3Jk2/PLi07fPvQxTOE4hdtsgxqH/rBLyFxQfbQzSwrHPW5TXSAHZzA8fP/xIcJYF+NITbWXvvWU1htWppo084gZaZhzpOlQiJjqEyv8Hdr5t7nohD1c2H6x0HPLg97ybWADsiXEB1LtmBoZ60WwcN9iSwsGVAYzkbSWn8JXX7d0nOrC0TVnKvtd6ru6p4yHoJW918y2aegJlGsOfICxCM2QD8DLg+nSzEu4ep83GMw1Zy/Dwm95UGlm9Hw+PwOVGGAfocgFewaCouDoh5OjGLxYAqrmw4KmWc+urg/y9aLpLfqBZzu9Pq2zQ/H29qBJ6pN1dLmVaD14kG9DxroMXI6o/6Mky6/6QgTyracDiz/RntG32DIbt9sYNKExW+kM91dXpXln7Iw+RihOjJz8NTF4Uf1hyodVOW+yvs+bphjICEoyGhL3gV+4Ojo2vo/9jdMqitfIu6uGCl0uWeA/MUctC+18IxysPo8KybmxjD/9Msdjls93DANcZE3GNcfUhMfxH0PuP/bqFdnUEILf47fNxZd0UIeANPxqxidI9fsHtwovohmdjFnFFTn7G2cSsS0cwxNwsZIPMmQ5wQWtGz9t2R+M4yI6lxD5tCru1sFrJFkQrtRrjkbWifcGZNdpRqrVQwGPIxYpyoUvmNZ
  template:
    metadata:
      name: renovate
      namespace: renovate
