---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik
  namespace: authentik
spec:
  secretName: authentik-certificate
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-clusterissuer-acme-letsencrypt-cloudflare
  dnsNames:
    - auth.47fc5c.com
