---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-redis
  namespace: argocd
spec:
  encryptedData:
    redis-password: AgDC+LsBHFL5cpSF9GL2s7mTOcLOiOK3pr7L5NIqeEyDfBSIOyj2YLtJtlqrooiUwo9RhZjqVNOJ4cfWXpnpgfP50Uc74I/ECysOV54mrnBOggYGLYtfGfh5QL41qLDg+FwGOHKorjdTxWimmCd4DHbQks4PVoCOYxqs5hc+MhAgC+J5sVU1gQUbkSZg5hZWa/B3UG+oH7c/qoooCNvTPHxnQw9HKVv1rI2ClXwwjIci5Oj0GXZ/IqPfnzsG4kEF44Cr8j36q/XLmVD2hNtz55kstVSCfw9Jr0YyCyQgV0ArLjZbpWYxlqb4ki1LBpY0PaBgaMvjmTmNSQFVXoUdPxJkU5Ls63b8BsPBxwulpCMje5F9kctmQrWN4jwITwLY1ZeXmB1pE6KhNf97/zVmD7D2EIMghOfT24ScbEdyBtxsZH1m0CS+SlAGXqZI62Bi10g8cin6ULwPHlZlu0CgFnPEjt//a3WDB9uHj0WJgdelXL+xnUq494WZT3E5J2i+0F0XNkL0XrpMt6stzbfv55s60VbUwQYcpdNycgflIeLpWT7YTE8mHw1dU/7VaH1BDr+/P3Vni0RfHT9mHfmt25S3x3EKbCrKsapsJB6eghNi+0nmUdzyGXFCbiUG7hmzDGHLXffIgSwxsTLoiwvpTSHHOX3vYgAQ/EBbTdQR27vCvl1wrNSMNHdEyQSxKoqK9V95RL5xVoRlAD2PWYIj5HCWkwcBx65jSQnMFPH/a/Mduw==
  template:
    metadata:
      name: argocd-redis
      namespace: argocd
