---
crds:
  install: true # -- Install and upgrade CRDs
  keep: false # -- Keep CRDs on chart uninstall

global:
  domain: argocd.k3s-01.47fc5c.com
  image:
    repository: quay.io/argoproj/argocd
    imagePullPolicy: IfNotPresent
  tls:
    create: false

dex:
  enabled: false

controller:
  name: application-controller
  replicas: 1
  metrics:
    enabled: true
  extraArgs: ["--redisdb=4"]

redis:
  enabled: false

externalRedis:
  host: "redis.redis.svc.cluster.local"
  port: 6379
  existingSecret: argocd-redis

redisSecretInit:
  enabled: false

configs:
  params:
    server.insecure: true

server:
  name: server
  replicas: 1
  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  metrics:
    enabled: true
  extraArgs: ["--redisdb=4"]

repoServer:
  name: repo-server
  replicas: 1
  metrics:
    enabled: true
  extraArgs: ["--redisdb=4"]

applicationSet:
  name: applicationset-controller
  replicas: 1
  metrics:
    enabled: true
  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

notifications:
  enabled: false
