---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-repos-encrypted
  namespace: syncthing
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-crypto-global
  resources:
    requests:
      storage: 6Gi
