---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: syncthing
  namespace: syncthing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      containers:
        - name: syncthing
          image: docker.io/syncthing/syncthing:2.0.15@sha256:1feffa2d4826b48f25faefed093d07c5f00304d7e7ac86fd7cda334d22651643
          resources:
            requests:
              cpu: 200m
              memory: 384Mi
            limits:
              cpu: 500m
              memory: 1024Mi
          volumeMounts:
            - name: syncthing-config
              mountPath: /var/syncthing
            - name: syncthing-repos
              mountPath: /repos
          envFrom:
            - configMapRef:
                name: syncthing
      volumes:
        - name: syncthing-config
          persistentVolumeClaim:
            claimName: syncthing-config
        - name: syncthing-repos
          persistentVolumeClaim:
            claimName: syncthing-repos
