---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: syncthing
  namespace: syncthing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      containers:
        - name: syncthing
          image: docker.io/syncthing/syncthing:2.0.16@sha256:4a961394ca471f4e48f31ad2cef50697e502c8799e2e98477a1c3844e0c5bc54
          resources:
            requests:
              cpu: 200m
              memory: 384Mi
            limits:
              cpu: 500m
              memory: 1024Mi
          volumeMounts:
            - name: syncthing-config
              mountPath: /var/syncthing
            - name: syncthing-repos
              mountPath: /repos
          envFrom:
            - configMapRef:
                name: syncthing
      volumes:
        - name: syncthing-config
          persistentVolumeClaim:
            claimName: syncthing-config
        - name: syncthing-repos
          persistentVolumeClaim:
            claimName: syncthing-repos
