---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: syncthing
  namespace: syncthing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      containers:
        - name: syncthing
          image: docker.io/syncthing/syncthing:2.0.11@sha256:905d4a8fac511e0022432d084413a2a8578a67036dc44cc3df184c4e6f20ec33
          volumeMounts:
            - name: syncthing-config
              mountPath: /var/syncthing
            - name: syncthing-repos
              mountPath: /repos
          envFrom:
            - configMapRef:
                name: syncthing
      volumes:
        - name: syncthing-config
          persistentVolumeClaim:
            claimName: syncthing-config
        - name: syncthing-repos
          persistentVolumeClaim:
            claimName: syncthing-repos
