---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
data:
  HOMEPAGE_ALLOWED_HOSTS: "*"
  HOMEPAGE_AUTH_ENABLED: "true"
  HOMEPAGE_EXTERNAL_URL: "https://dash.47fc5c.com"
  HOMEPAGE_OIDC_ISSUER: "https://auth.47fc5c.com/application/o/homepage/"
