---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:v1.11.0@sha256:b129cb0f674bd6d204e215bde2c2fc3f11d6ad0e82f6d20007cf80f74e1acbb1
          startupProbe:
            httpGet:
              path: /api/healthcheck
              port: 3000
          ports:
            - name: web
              containerPort: 3000
          volumeMounts:
            - name: homepage
              mountPath: /app/config
          envFrom:
            - configMapRef:
                name: homepage
      volumes:
        - name: homepage
          persistentVolumeClaim:
            claimName: homepage
