---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:v1.13.1@sha256:d8d784e5090111b6e4c56dfd90e272d2953a2094e87349f647165df0fa6c4401
          resources:
            requests:
              cpu: 1m
              memory: 96Mi
            limits:
              cpu: 15m
              memory: 160Mi
          ports:
            - name: web
              containerPort: 3000
          volumeMounts:
            - name: homepage
              mountPath: /app/config
          envFrom:
            - configMapRef:
                name: homepage
      volumes:
        - name: homepage
          persistentVolumeClaim:
            claimName: homepage
