---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage
  namespace: homepage
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`dash.47fc5c.com`)
      kind: Rule
      middlewares:
        - namespace: homepage
          name: homepage-ipallowlist
      services:
        - name: homepage
          kind: Service
          port: 3000
          scheme: http
          sticky:
            cookie:
              httpOnly: true
              secure: true
              sameSite: none
  tls:
    secretName: homepage-certificate
