---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dawarich
  namespace: dawarich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dawarich
  template:
    metadata:
      labels:
        app: dawarich
    spec:
      containers:
        - name: dawarich
          image: docker.io/freikin/dawarich:1.11.0@sha256:4e3c55c4cd572373624e75c9e02075ff436c83a3ea952595ae0d4ffc4c7ae52b
          command:
            - "web-entrypoint.sh"
          args:
            - "bin/rails"
            - "server"
            - "-p"
            - "3000"
            - "-b"
            - "::"
          volumeMounts:
            - name: dawarich-data
              mountPath: /var/app/public
              subPath: public/
            - name: dawarich-data
              mountPath: /var/app/tmp/imports/watched
              subPath: watched/
            - name: dawarich-data
              mountPath: /var/app/storage
              subPath: storage/
            # - name: dawarich-db
            #   mountPath: ??
          envFrom:
            - configMapRef:
                name: dawarich-shared
            - configMapRef:
                name: dawarich-dawarich
            - secretRef:
                name: dawarich
      volumes:
        - name: dawarich-data
          persistentVolumeClaim:
            claimName: dawarich-data
