---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dawarich
  namespace: dawarich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dawarich
  template:
    metadata:
      labels:
        app: dawarich
    spec:
      containers:
        - name: dawarich
          image: docker.io/freikin/dawarich:1.14.5@sha256:11826c67e4b1cfc1049033b5b6ad05f5134bcbfb7807045bd39d3376cbc79d89
          command:
            - "web-entrypoint.sh"
          args:
            - "bin/rails"
            - "server"
            - "-p"
            - "3000"
            - "-b"
            - "::"
          volumeMounts:
            - name: dawarich-data
              mountPath: /var/app/public
              subPath: public/
            - name: dawarich-data
              mountPath: /var/app/tmp/imports/watched
              subPath: watched/
            - name: dawarich-data
              mountPath: /var/app/storage
              subPath: storage/
            # - name: dawarich-db
            #   mountPath: ??
          envFrom:
            - configMapRef:
                name: dawarich-shared
            - configMapRef:
                name: dawarich-dawarich
            - secretRef:
                name: dawarich
      volumes:
        - name: dawarich-data
          persistentVolumeClaim:
            claimName: dawarich-data
