---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dawarich
  namespace: dawarich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dawarich
  template:
    metadata:
      labels:
        app: dawarich
    spec:
      containers:
        - name: dawarich
          image: docker.io/freikin/dawarich:1.15.0@sha256:56be3eb19c9a1d735217e8c16283a9ec63e47d91d9d70cdd23102181d51b579b
          command:
            - "web-entrypoint.sh"
          args:
            - "bin/rails"
            - "server"
            - "-p"
            - "3000"
            - "-b"
            - "::"
          volumeMounts:
            - name: dawarich
              mountPath: /var/app/public
              subPath: public/
            - name: dawarich
              mountPath: /var/app/tmp/imports/watched
              subPath: watched/
            - name: dawarich
              mountPath: /var/app/storage
              subPath: storage/
          envFrom:
            - configMapRef:
                name: dawarich-shared
            - configMapRef:
                name: dawarich-dawarich
            - secretRef:
                name: dawarich
      volumes:
        - name: dawarich
          persistentVolumeClaim:
            claimName: dawarich
