---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-data-encrypted
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-crypto-global
  resources:
    requests:
      storage: 6Gi
