---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-crypto-global
  resources:
    requests:
      storage: 2.5Gi
