---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  sources:
    - repoURL: https://gitea.47fc5c.com/fraccs/homelab.git
      targetRevision: HEAD
      path: kubernetes/k3s-01/workloads/traefik
    - repoURL: https://gitea.47fc5c.com/fraccs/homelab.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: v34.4.1
      helm:
        valueFiles:
          - $values/kubernetes/k3s-01/workloads/traefik/values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
