---
image:
  registry: docker.io
  repository: traefik
  pullPolicy: IfNotPresent

deployment:
  enabled: true
  kind: DaemonSet

ingressClass:
  enabled: true
  isDefaultClass: true

gateway:
  enabled: false

gatewayClass:
  enabled: false

api:
  dashboard: true

ingressRoute:
  dashboard:
    enabled: false
  healthcheck:
    enabled: false

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true
  kubernetesGateway:
    enabled: false
  file:
    enabled: false
  kubernetesIngressNginx:
    enabled: false
  knative:
    enabled: false

logs:
  access:
    enabled: true

metrics:
  addInternals: false
  prometheus:
    service:
      enabled: false
    serviceMonitor:
      enabled: false
    prometheusRule:
      enabled: false

global:
  checkNewVersion: false
  sendAnonymousUsage: false

ports:
  traefik:
    port: 8080
    expose:
      default: false
    exposedPort: 8080
    protocol: TCP
  web: null
  websecure:
    port: 8443
    expose:
      default: true
    exposedPort: 443
    protocol: TCP
  ssh:
    expose:
      default: true
    port: 22
    exposedPort: 22
    protocol: TCP
  dns-udp:
    expose:
      default: true
    port: 53
    exposedPort: 53
    protocol: UDP
  mqtt:
    expose:
      default: true
    port: 8883
    exposedPort: 8883
    protocol: TCP
  bep-tcp:
    expose:
      default: true
    port: 22000
    exposedPort: 22000
    protocol: TCP
  metrics:
    port: 9100
    expose:
      default: false
    exposedPort: 9100
    protocol: TCP

service:
  enabled: true
  single: true
  type: LoadBalancer
  spec:
    externalTrafficPolicy: Local
    loadBalancerIP: "10.200.1.10"
  # clusterIP: "2.3.4.5"
  externalIPs: []
  # - 1.2.3.4

hostNetwork: false
