---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tubearchivist
  namespace: tubearchivist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tubearchivist
  template:
    metadata:
      labels:
        app: tubearchivist
    spec:
      containers:
        - name: tubearchivist
          image: docker.io/bbilly1/tubearchivist:v0.5.9@sha256:b827a713f55b2b1933f8b130f36dc8b38cec3dd56998c389b7c9694a7238f3df
          envFrom:
            - configMapRef:
                name: tubearchivist
            - secretRef:
                name: tubearchivist
