---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tubearchivist
  namespace: tubearchivist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tubearchivist
  template:
    metadata:
      labels:
        app: tubearchivist
    spec:
      containers:
        - name: tubearchivist
          image: docker.io/bbilly1/tubearchivist:v0.5.11@sha256:f7bfd5cc8d9931c752d07206f082440a56d88eec595a0a5d684dce762b402d64
          envFrom:
            - configMapRef:
                name: tubearchivist
            - secretRef:
                name: tubearchivist
