---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: docker.io/library/redis:7.4.7@sha256:483eaf69e400c5254a2dae9c9f9499c336ecc0537c36fca462516a8f8bf75f78
          command: ["redis-server", "/data/redis.conf"]
          volumeMounts:
            - name: redis-config
              mountPath: /data/redis.conf
              subPath: redis.conf
              readOnly: true
      volumes:
        - name: redis-config
          secret:
            secretName: redis-config
