---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: docker.io/library/redis:8.10.0@sha256:344e3945a0b431c8ff1eecd58c5573538126bd756f02fc7e218ddf1fc2546366
          command: ["redis-server", "/data/redis.conf"]
          volumeMounts:
            - name: redis-config
              mountPath: /data/redis.conf
              subPath: redis.conf
              readOnly: true
      volumes:
        - name: redis-config
          secret:
            secretName: redis-config
