---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: docker.io/library/redis:7.4.7@sha256:d665ad9dd15a25c100b77134516d4f9f46f06884983d86456f0a9c0434f3b49f
          command: ["redis-server", "/data/redis.conf"]
          volumeMounts:
            - name: redis-config
              mountPath: /data/redis.conf
              subPath: redis.conf
              readOnly: true
      volumes:
        - name: redis-config
          secret:
            secretName: redis-config
