---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: radarr
  namespace: torrenting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
        access-postgres: "true"
    spec:
      containers:
        - name: radarr
          image: docker.io/linuxserver/radarr:6.1.1@sha256:cd70546fc97169788530386b42cf47ba1b16d091b4dc2264cd54099dd13c6f7f
          volumeMounts:
            - name: radarr-config
              mountPath: /config
            - name: radarr-downloads
              mountPath: /downloads
            - name: radarr-movies
              mountPath: /movies
          envFrom:
            - configMapRef:
                name: radarr
      volumes:
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: radarr-downloads
          persistentVolumeClaim:
            claimName: radarr-downloads
        - name: radarr-movies
          persistentVolumeClaim:
            claimName: radarr-movies
