---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: radarr
  namespace: torrenting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
        access-postgres: "true"
    spec:
      containers:
        - name: radarr
          image: docker.io/linuxserver/radarr:6.3.0@sha256:2b2c1c05eb3f648d2c80dfab9486147dd7bb0ad4d77fa972fc1c5de8f1da3738
          volumeMounts:
            - name: radarr-config
              mountPath: /config
            - name: radarr-downloads
              mountPath: /downloads
            - name: radarr-movies
              mountPath: /movies
          envFrom:
            - configMapRef:
                name: radarr
      volumes:
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: radarr-downloads
          persistentVolumeClaim:
            claimName: radarr-downloads
        - name: radarr-movies
          persistentVolumeClaim:
            claimName: radarr-movies
