---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: owntracks-recorder
  namespace: owntracks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: owntracks-recorder
  template:
    metadata:
      labels:
        app: owntracks-recorder
    spec:
      containers:
        - name: owntracks-recorder
          image: docker.io/owntracks/recorder:1.0.1@sha256:050c3ac9ed798d4110f12e53851e94f9fa0fcecb16cf4d7457967eac2e498da7
          ports:
            - containerPort: 8083
          volumeMounts:
            - name: owntracks
              mountPath: /store
          envFrom:
            - configMapRef:
                name: owntracks-recorder
            - secretRef:
                name: owntracks-recorder
      volumes:
        - name: owntracks
          persistentVolumeClaim:
            claimName: owntracks
