---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: owntracks-recorder
  namespace: owntracks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: owntracks-recorder
  template:
    metadata:
      labels:
        app: owntracks-recorder
    spec:
      containers:
        - name: owntracks-recorder
          image: docker.io/owntracks/recorder:1.0.3@sha256:119b9cf15f5f45bbeab1b7f87b41948adbb9ba210900e188be21f384cdd7600a
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          ports:
            - containerPort: 8083
          volumeMounts:
            - name: owntracks
              mountPath: /store
          envFrom:
            - configMapRef:
                name: owntracks-recorder
            - secretRef:
                name: owntracks-recorder
      volumes:
        - name: owntracks
          persistentVolumeClaim:
            claimName: owntracks
