---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  encryptedData:
    DATABASE_URL: AgAEra2Sdo2pbwzr9lFBv9QxHa2imlNGpfvRrU/Y1XTbuJ5UPSrkdwRSvpve50db1ush0pqgBIoH97D3BfsmJ8jI9eW74s/uAsTDsQwZIcg8ET7P09R3spjrYGo67tzoS7tNfnyBfqoWlmRQB7+zvgAYAv/NY14+xxle9ZppCJndGhiydXIKR2qvy/t0C5zg39j1LvYBSB4swIbbwO84DnitJ6c0GhmBWzT1JRX1YcfdzRqPMuukhxTyx0UOBEc1O4kQzqZ+WBVaaGV9XerI+4lIzNt2AKCf8KEh2UcfK0+ahA7YfCv9CBW08BsqMgs81KlTLuI0imgB0d3aukeegpKKcHwArxkntli9FqcZIb8RhXI9S1iemZQCKh5LWndx0Q3r6UNLDo+j1wZvgSUW1oVw8GnXXaNtIudQBeZWn+4N0Wk4GEa7l01Ae2ZsVjz3HB2JdlXSnQeKZbLrOl/8OZJir+lXd2bLOIdBZCVCJzYH9upuyhV2NqRAqJzZ7N+WoVofX5Ap3yi9wCVnKGgWmE4cNmZjDFbZeiXAh6M5Rje9Cf1HvUHaibqaVUv9ex5ejOHtYgZm2gWAh+QwBEXMsknOZpnqQD3TyIIp8JTcB18p9tbMW20/o9WgcXsUWBe1Ikp1v8iiJk6ulyCzzwS/tRMn2UisZppDllBid+TFJZwpCtLl/KCsan7lvYhaTcO1Tl3fXlN5dswwJ33kUEmkygcw6ynbq3T6rFH2WiMfMkqa9P9yGauaCWz0d9Uzn8jR3AvpJfbX5VndYgXVN1Qm02QMLFaVZmw5w+Dz9hveRDs/J2Upv+JDWZAZbN37oWIX
  template:
    metadata:
      name: vaultwarden
      namespace: vaultwarden
