---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  encryptedData:
    DATABASE_URL: AgBmMNsysnZkV8C76thzlxIMen8uCmUUJYTuyJ8Uwymfd5/1dVe3d1+Ty2XZ8yNkvoHs1KMivyiQv789/BwRrmnovvFOM9mprYaveC+ky60ScjiryDMaPYXEoKcrWrzTM+LkE3DrYpR1+Cn4edUqNn2W4PTY+f+P3OIPXDyGLbquthAb0fkzZpSc73wLM76dpnNMTh3+eMW4k8tVDolY6UVlNqTviKt1gb3cIjjMjYoYORtHDSE/PdXsxP77HZbuy+f+1mtIP5mycznHuk5dyvE1KpHfAI1Bn4qiHJ9Ifo9rb8cwJwEcBaYVJbFAb8+DEJmAefOeOQLKix+WcKh1koaXxjGfjbxilLsPG/Fc8uK+zI/8wLu9TCZeJaZ9vnS/lTM4KaQJBq7v/O1JTfGq3gZFugAzHURQJ++EUlfjoiv3UTKN1NRB+cvVjvC/lSvWGExo9qOLMvGb+q7fnQ9tGEY+ksX7AfygIwci7NTRT//unFePhXyfHZQLkls9nrFVboNKGjU7bAl3lRgY/wwwNTyotonB3SzD5EzS7M2UiqJmgF9k70rT/u62dmo/o+WWeugk/WpLqnanV93+9/dE73CdHYxCf/PUK2JZtKQ7Cjqg9F6sRble1V4QGwGj0ECKrDoGo4IrQSgRFQapE3b8sJmLfcTefpos0BLk47cbA8sZHlArtuzZ3fJYfeyr0hcWAhljDHxJ6Adfri8Sl3VyDiOQHSHN1LB7DSCalukK9SCjJB7LR8HjergDtG81IEqU17sPARZDi14fdVq8uSaJOD4/b0GoqJk3cWzYLAo7hmyNjvFAqzNocXeIO6oULP+gjM0F34eBD/Q2Rwg38lcyrE0bsMDH00s=
  template:
    metadata:
      name: vaultwarden
      namespace: vaultwarden
