---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  encryptedData:
    DATABASE_URL: AgCBeu8sLgJ0B0uus1k09ULvdofW7cWhLPhjjAn7naLkn5kGPKPP0chiSOnIpXowwJMNO1FworSsFQcgI4sK+OFXl0KNEw4k1GXbu/RrY3HIWKcEne1hVbdnOw7L3m5uNApWNWGz9LNBBMtQtvXwFRh8/m7AezIwokwBxXbEUNfZMQa/c9pOXCDMeTT+0DpKi7scy8taw7nhXIUM10r8zTkHTZWTo/IhMRGaVpKfwd11GBt3XZrlPBR6N0sNn4fvUgZh9hLC+1iSDfzfQZQJgniqvv2XASKjGmwjv7O1iVQLNyFZhxP6S3q1Fh3WqIt+EndE4/0rhAuCF0lW0iSkcplXARiEdVMfxXxDanCLrhEt804r6uTihH3IPicykELy8g7AaeOg4CPpM4lx/zDnToZA8LjVboR43eS9Ifbw7QG+7lYHcAPrBLyBo35PbmPQmLSamEMv2+AA15+5O37NdNwdQAFyGxppD7wvnguQIEiflxaCTlDf+qp6vtLSKbluEDN9kw4z6xYJkXbSPTv5A3Tos6VZjtOzSOeLEvrZqwpcjVvModOwEp6CgOITr8DYPJHwsQHbmqYqcEaHUo93BFIRoeOgh/xLKtHKPhX7quxjNEShAbWCZqZW5FDUZRiAlUPemioRLEy4T0ReYThIwH4aB3Mg4L5Aya/WJXnrfPEELRc2zkmi/0AjSkjtffGAzo9o42rInhVckCxGBM1Laobxc3VlB3rT4Xi02EJgVx70j5XJMGH00tjh6XyuXz3B94JfS7TGHzaJvx+bUohSALuGn+ZgbME7e64MJZgLcHUZOWKZE+Lx6ukcN5TFjyTsJVvxjU8oYi1VprpWGdSEACEsdpVk1VTS
  template:
    metadata:
      name: vaultwarden
      namespace: vaultwarden
