---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  encryptedData:
    DATABASE_URL: AgC/fnPjyCmceQWliH4vXZeIWnjTpenboPvQ1009k0jO2PRjGdbXZ12EPOB/o2nVapZis2gQk//lOmvu/HSi+oyKqJ7KfnXyidf8Tvn8kcZDjr3qLH7vkhBegmnURiMW1/CDkrmVrAXFlQXudBUpfhZmb1genKFP/ty1w36LkH9cFPGKq8xCh89DZSeVyGp+jIPA3Vwxb2UEM55fmtT9TqmYfpcHePDeVpuaPDCngRbZm1J/xJAqV197cn3F6r/idBNHsNx89Eb4OdxG9X16TxMGIdXEwBOD/AnaF8mcJmzRggOA6J6RPLVGve1AL1xr1Np3Q6ZHClcKdpKR7D1NT+2+gSJfJhVCa/6J+4Tv292O2QtFkmm6/akHBEjC2l+VowSstEc6dQr3xZPEEK3hKx2UFKTZUC/a9h5wZnAVEeydLybURDbjxqF5MALN+8zP68UV8/jhSpRcZyrKcGK/eegtaa1dz1QHiIE9dVpTYcV7b+J8MPuNHLzI6CWIAmm3sZy+DvSSgKnwzylbLADz2vwVtr99y6frOHWLEIVQSFtWh0ZPODQrIo2AKFbYRnaFeVFMNlbtrXGIMAdC6Ju3L0w5w1BWPv+gAjAQUAckBuMdaB3WuNg1ojMZS6cgu1azrQp6aQF78nRCcR2jDM9sLb1lbxqF5dDfuHiI40CZZY29JOgN435V5SlK0HVZD0Kf/+TI0FVPH2v8ZMyPvSLkw9Idq0QtDAVRA7fTXdTQYgNNx6jKCKRNZ9Mx9zs9G+4Y2NN1tXdPxq4HrO6uC3eSRVweQB9c4DvkCjhG+rs0S1a1lotRmy8pmI6q1IOGpZ/Vr6fCkQ==
  template:
    metadata:
      name: vaultwarden
      namespace: vaultwarden
