---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: archivebox
  namespace: archivebox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archivebox
  template:
    metadata:
      labels:
        app: archivebox
    spec:
      containers:
        - name: archivebox
          image: docker.io/archivebox/archivebox:0.9.36@sha256:87bdb24068eabd140695c2c1333dc4952f3f76ba176f4b5028d07031c67a31fd
          volumeMounts:
            - name: archivebox-data
              mountPath: /data
          envFrom:
            - configMapRef:
                name: archivebox
      volumes:
        - name: archivebox-data
          persistentVolumeClaim:
            claimName: archivebox-data-encrypted
