---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: archivebox
  namespace: archivebox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archivebox
  template:
    metadata:
      labels:
        app: archivebox
    spec:
      containers:
        - name: archivebox
          image: docker.io/archivebox/archivebox:0.9.64@sha256:5cc01b315cb11b9f018215e40df5fd498f2b30b6f7304f758cfdab4758d9544b
          volumeMounts:
            - name: archivebox-data
              mountPath: /data
          envFrom:
            - configMapRef:
                name: archivebox
      volumes:
        - name: archivebox-data
          persistentVolumeClaim:
            claimName: archivebox-data-encrypted
