---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dawarich-role
  namespace: postgis-cluster
spec:
  encryptedData:
    password: AgAnoK5OeLpVgQH2Yvwd2JBxjRpG4vYbCKbPieLyxuo3OWQvXO7pT2k+iZrBrNVDjwObJYrRvrjgZVfPeNctgkCQE277Au0upsFwYsa9DGe8d0sd64t+O+6ILMN9J8MG7ChqNEF0p3u3ZvmB80RIOCca4AqJ5BikphnWGX6/pTal5bkU8NyPmYB8siZ1DEZZvTc5gQJxdAJDY5FEqp4XD9jCXgyAV1dMy1pN8W9C0q8KJlEE0jatN5TBOvk47j4wBxutJGLAHk21Y6Sx9PmgcoODcwtJxzsj3oLyj3Np9ybfhnx1CoSnW/lMBuBNbweng+k+kidF/7gqnDhM+Pxr1VOT73fJ0uga8qyMz5FFRZPL0e/cW4DVxOxRkJ6kDimLT9M5kAi0z+Yk2HjclWhVmvgnk/S+7ArjyRMAI0aZJ6HXrzwBzR6hBlxRN9LBxmYV1atQVbi7gRnPT8AqSB4aYtvI7e1VgjE1xAJNFHp9qVL9xI8PC3DqKuNoBSVDjP/o+guhmWVblhBgLTahHjkZNTcMKBigOPsjF66qyGIN8/rjGXnYz18oteBM+0Ej9FyhcNOQmfvHpojDUAsMeUdGPmZvTehRvFysxoG1+KNRMgu1ZM8xjRZHdDVyRSKqaeuZm+VIRCQdV9j09hYNupngh975YivSnP3kXByMg9kSTzd39dgtmJPeA2ennSZ4grOGDhAei0+atLDuEufT3J535SjCNGMydw0Md32HvBtiDmpxPQ==
    username: AgCU92fcZfZnkGCS2J4oPGBxBTdZPxzKXRz5ynU3GMzLNGFYdEmEaxyI6jbnr7Y+KV2gabgOiapi00bVeesnCxNhydONpsT5kVNbLzlMvxrcSmJU1v7O13t6BcJeiPDf5aSRv19IC3a+yo2pZ9D/Xv3fRHkgLAtoh4uP2+yl/dxl3FvXqnEa3k42Vu2L6ZL+YuqZ4OmYqL0i4JOTMz/Zg4UMN3L2c4U0ERDjpk04VUU10jdCS+tVaImTTWZTzG6FPSZ7mBnneZB76vpCqHDNd0e+IG8otvYf8kOhC1ye0/gMP0hEhnkPcNuJ8St+SIUyL2zSuurRSzadQdQj28b1iH2usy4ZqM1FWsyhoV5ZaYgFb0lDbIfrRj7QHmeX5NA2NrvzTP78edYotPVOTtEN/pqQTcIaqI4EHXNthiz7w3xYimnJYYenUebn8iIrz71UygL610RBzafVDN+3CtQI2OkvEYXKWDX6UYhxMjNmK83h1GCWJyNGMvRiIVj0GqxRPbhGuzUxz9KoPlXXURlNirpGNAIupSFaeUsV4ylh1iRaXYDleGb/GdFpR4nUBuPkl5pqa84KRp03XGqvzXVcOrasPa7AbM7cjfY3P1AU+egPeDpJbCEl9TSYAP3dnxgLwo00ZPTd9ugHeUanHI30h29x+HS61AMp33S9Gfe0pT7AmciLPGjV8lc7xCcME6M7L7R7cX4/dzFFQw==
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: dawarich-role
      namespace: postgis-cluster
    type: kubernetes.io/basic-auth
