---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-config
  namespace: minio
spec:
  encryptedData:
    config.env: AgCYpkfpcTb7ikQ1K+ptXcfFSRc2kHvjERQ1ZITIjLX8sCcE3B5cogjlkTesizApg6Ey6kIVVzC6CdEVozFEnTKhw91zyLfBvJU7G6Lwc82B5mBmjCkCC6IYLhqsVj8oVNhQ5kQQgXzgISGYGo3L4F3V7dH5DgrZYfDYMJiRJtrPfTktcWKYX6dUHFRuLiZdZBIexQW3chRVAYC3Agu82Imx6yhO964mCeSzbTliPg5lhW2CRzWqp7XPNLv0g4c4HmepQ9kfmTYbVgF4UyXfJ8Zlv9myBQzn8r6y2ZoMo2fMJh0mUCMA73ZxJs1o4gLSfbVDMn1BKuuLyW5KnUD0mIhNn0SE5HTeuOXyepDbr7z6dYoC1A/IIUTPGRg+UrQuv/5KcgvHlqE/yaW8b0N9X6hrp+SNZv+JVzErO2/HjVswW4q3Z5pHHUywNr81yi/nAJMZ1CBl45jQC/KxOq01xmEZwkM0IM5LYoXWJS+pSKfriWtqOH5mkF3CL9I2NUJKcdWcm5dWJlkUP/MioTPljo0Qf1oYC5pPfKnl4mZjXR7DpLhmSXfIoddx8+L4YJ/nczWx7LONOC+vC1lJTHhdZ8f8RGWAiEoe+KiyHmuV63YZiQ/lSw8iUOKHkiGQ0I3SuxMPfq19/rnT8V/Q7uTdeydCo2m4TXycyu1/E/WTVcJLWmGZIzQ/JzTjsszM27NrCj9ktiWSkJ+C/HX3Y1PNIoaLWGRvWTcNaCnAHuuPJlajrKj8h5NvC+9Bgqemo/Cs8BatahymxzJbnbe2NuD7UegIz3sx6ksvX66p5srw6Nz6TPxBxHUkUA5HwFDq1yga+2xamjb63PyhsA2rDTLGehUwHK1hLioTc/4hmZsRdLZNx31qwfBke5c3qsS3nJes+XAgq9JT9F7CUlnpE3pM5aHJjhZBbrXeR5+kqlN2HSdfAR+kuiOVtQqrHwjCSkzzDimpjCzfvhS97O9LvN6eOoqFyi6zolJhR70JIs1DbVdQ1vvaiZHES6EaGTko2yz51X9/ByeTjDKfw8mgNef7zuV/GjSZAUQD/b66GUJasHa5peVpN5LajPoomTuJWEd9bczmIkqEiRT2M+ZU8NnZg/FLNwtGkb5BMpQakfBSjeZYl1YcfGW2PQDEGJVf2I9WEBZduUHjw+kJaTlw2DNC0zsRrxmRS/CACAwL049D/LGOnD3ma3KzvXPDIo3DggusLDZuf6H6HUe9BQ58JGgRSJnWCpNnDCFW8RX91ErQsOviHbpV
  template:
    metadata:
      name: minio-config
      namespace: minio
