---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita
  namespace: kavita
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-crypto-global
  resources:
    requests:
      storage: 250Mi
