---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qbittorrent
  namespace: torrenting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: docker.io/linuxserver/qbittorrent:5.2.0@sha256:f76c4363cce0834df43b097682928d217f9f0e0fa1d13781c0934848d543e4ab
          startupProbe:
            httpGet:
              path: /
              port: 8080
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: qbittorrent-config
              mountPath: /config
            - name: qbittorrent-downloads
              mountPath: /downloads
          envFrom:
            - configMapRef:
                name: qbittorrent
      volumes:
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config
        - name: qbittorrent-downloads
          persistentVolumeClaim:
            claimName: qbittorrent-downloads
