---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qbittorrent
  namespace: torrenting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: docker.io/linuxserver/qbittorrent:5.2.2@sha256:bca2cf536c00900f0b8fb62ca3dcbed8ee64293165d41c8240d2cc952d4ef048
          startupProbe:
            httpGet:
              path: /
              port: 8080
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: qbittorrent-config
              mountPath: /config
            - name: qbittorrent-downloads
              mountPath: /downloads
          envFrom:
            - configMapRef:
                name: qbittorrent
      volumes:
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config
        - name: qbittorrent-downloads
          persistentVolumeClaim:
            claimName: qbittorrent-downloads
