---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`homeassistant.47fc5c.com`)
      kind: Rule
      middlewares:
        - namespace: homeassistant
          name: homeassistant-ipallowlist
      services:
        - name: homeassistant
          kind: Service
          port: 8123
          scheme: http
  tls:
    secretName: homeassistant-certificate
