---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
        - name: homeassistant
          image: docker.io/linuxserver/homeassistant:2025.10.2@sha256:a13e1a3ed664435a223985cf5646b2af8c0d40b777bd3bffceeb12ccb51cfb60
          startupProbe:
            httpGet:
              path: /manifest.json
              port: 8123
            periodSeconds: 30
            failureThreshold: 10
          ports:
            - name: web
              containerPort: 8123
          volumeMounts:
            - name: homeassistant
              mountPath: /config
      volumes:
        - name: homeassistant
          persistentVolumeClaim:
            claimName: homeassistant
