---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
        - name: homeassistant
          image: docker.io/linuxserver/homeassistant:2026.2.3@sha256:1db102869a0aa63b3a51f16d9bccf910c871b52e6925448a02bcde1f05d2a1b7
          startupProbe:
            httpGet:
              path: /manifest.json
              port: 8123
            periodSeconds: 30
            failureThreshold: 10
          ports:
            - name: web
              containerPort: 8123
          volumeMounts:
            - name: homeassistant
              mountPath: /config
      volumes:
        - name: homeassistant
          persistentVolumeClaim:
            claimName: homeassistant
