---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
        - name: homeassistant
          image: docker.io/linuxserver/homeassistant:2025.11.3@sha256:51a4d1ec3a119f9cf62c4da0e4c81b2a235b941860a415efe32e9a10f62ba210
          startupProbe:
            httpGet:
              path: /manifest.json
              port: 8123
            periodSeconds: 30
            failureThreshold: 10
          ports:
            - name: web
              containerPort: 8123
          volumeMounts:
            - name: homeassistant
              mountPath: /config
      volumes:
        - name: homeassistant
          persistentVolumeClaim:
            claimName: homeassistant
