---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hortusfox
  namespace: hortusfox
spec:
  secretName: hortusfox-certificate
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-clusterissuer-acme-letsencrypt-cloudflare
  dnsNames:
    - hortusfox.47fc5c.com
