---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hortusfox
  namespace: hortusfox
spec:
  encryptedData:
    APP_ADMIN_PASSWORD: AgBj11FMWLMLSxB34FDAQfycgPKTqqNenDMvkbmWcEf1PlxrfOKLfcy7H606KHc7VH2Fc4fffdKEOUGJs39bHG1b8LOj/4thB/0ak8wjg6pokpChXLBupr+3cR2z9t7Q3r77IvfxJ17Ca8+MbC57t8U/D7xSJqqx8fgWiQXPguiImeFTj6XC2WM43ulr83rwLnmrzzvtGrdz1mpTup4q4/xbjKrPSBoiwD8PVQYajewYs3mAxDWtYoUys0331dXEOJEvLW28O7HDuozc9rWmD4Y26lUEcbSlqQIvso0W3zW4tv5qO+VOCiMB1TOOYuRFsxXzijeZGwU3SzGg8OXgaEYVGY+6OG0D+3sIgj/tI8aT2Vd+0dXflqpYd+AmZ/bsN/PdKoe7SRVCVOojIKtjbPrjfZrYe+kSSrfySKpOyPjg94bvZcDSfwOzn3QvWdzuARpU0PxpRlLKZU+JzwKdn7zArrCZpp3+mcPDnXKWktNmiXd9NW0nVLdZN2mH2oDumpWs7REtSk62fbgyQFfq/9hh/lBWBZQaDsyKNY/RF0H1ZgTnJvf8dNURNVaPoPBQwoM1aDTIJQSnaOZMAI48twiDUA1LUlgJq35391BJ5mx3joELq7M2Q2HgNkcuWm+lKCWnJQvBbzQc2ZEX6RivHFYBsw7loEFsRaFaeDBnD/Q6Gpx0d8UtqgGP0HBkZyI1bX8EotOtoSF/O45hQMjb1sacN7ePMsrcYC4=
    DB_PASSWORD: AgCUkfzKbFE38e0wJ3hDDO7DohiIDF8aI9N2kCvFNP6y91i/edBNmQgaYVc/+qNgFVq39AvyavFSPb/eza9d3NiZh0+tWQzr3Bgd5Yw8V6IaC8PUHqz87lk/NISX7+16bQlo/KpbCLkAmt5TcyAAZNN4GOaEITbFVuz/b3MHVYhF8X0I3d44WxYk9qUkTceL4TrOQ0uY8+OOpZp/EGyQBJn7FHy2wDg7nxeykI65oxguqH4szkjoC4fZhgz8k6ni4lGLInHkBajk9/31bQzGkQCbtUb91AZs5KJsWDAAkShd8uR9SBHMA3N1SLuttxktnzCQrXy77E40k/RvVXQSGnSdYb9uTGQvE4bXqS0DE15hX2i6YJYYpkGary2Rc2aTVHZ4czG1F9TLNe8aUpHtH79V0RiMz5iZuaaltPk4vDP7Ijuw3SRUmiLVBkRDblqKDufD6CYXt/fsT6BBn7wFzS2H6xcnA64qdsKFGdCprFn2fT61fay3IADruWARNRUXsJPW4eR62jfbcm5ltO9TK9rvX+OEDSGhbQa+b2rIyjo1VDV3p8pVWffw03GL4uHC7+l6RLuq1trwL1aiiwk6C64AG862WcJ1hB8NOhG1AuwmbQ+zmViqKSjrMbuZRCXCfA8JW4DPszAr2RF2QYm0raaVP6xvN2aQvN12m2SDW0Sk2f84HbA1O0yYsUVYA958u3qqHemaD7nZTiw1rKMDzIgVcM/jLKPmZlh/ICX95jujOA==
  template:
    metadata:
      name: hortusfox
      namespace: hortusfox
