---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: airtrail
  namespace: airtrail
spec:
  secretName: airtrail-certificate
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-clusterissuer-acme-letsencrypt-cloudflare
  dnsNames:
    - airtrail.47fc5c.com
