---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airtrail
  namespace: airtrail
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: airtrail
  template:
    metadata:
      labels:
        app: airtrail
    spec:
      containers:
        - name: airtrail
          image: docker.io/johly/airtrail:v3.12.0@sha256:c5616704defabd82d2dde97e93a5417e59c7acfdb06c0e589209257543b50f8c
          envFrom:
            - configMapRef:
                name: airtrail
            - secretRef:
                name: airtrail
