---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airtrail
  namespace: airtrail
spec:
  encryptedData:
    DB_URL: AgAOEzO8VsnsSK20KzSlbMzInM0LCY9WNuOEDWqwk17a7Bh9iQCRRXA8CVH29YDQHDifLHzEN1xlFnXXnFyWPACr7OtGOM3YvwLFcH8PUCPYnUqQ+1ZeIYAae4PuuMdIMHRW68RMmvl1SVwrbADiMDxG8aoDpjkVQDSMNYT7SCoAwybr4TKzsryW6lyHizdRNncFaiBACQZR5v5irM2xXaXs1tU0QwAbKT0BCqdF+7NJc9O3EnP4JNr63t50x7huJuw+i49IooycZiYfyVU0ieBpz7yXWd4WFXe6NJ2Llk/cZelycb/ErHP+7eir6rre88LoH8FOQAvDOrfIeXBGCXxdEZY0KzMuLOj5W7Xf8koqP9jFqSXCyOJu3EZ0QVYT5WCaEO7BR82oPl4iJFclRWGLR0p6mAwA0+aiDXSZTDTOn6ax/dEcqS1VgYuT70YOQn5nqePLoRs1CXt7tx0nH3XTFiwas8xqAB1UkFXW3kmQbejR3wZ7DMWpaGYmxVbKe6FDV4VS1uZzzCXAuNvtwA+SQgUDwHe4HNvH5ZnU8EYVcSlns/wX4694L3hUgxYoj+KHONiUlc8rPZNO/0a3sMohuyp8MPpdmqyvqRVkgVrKKroMKfmC6nWlwAPjzGpljGgTXDH71tDqMurmZawiprFD3hu1t40x2Uo+hBaZqWA4lvlX2pb/qODVA1yT/4LXijMP2tIqka9ZNuqnELT1E3PxVWhQVkTuD9RaO8cLC7VFSbShOyfGhEpItREAZANQfxM1P3SJgtN9jwYDUocnlOpUbWlIjnExoH+TBOxgDpbQiRtqYSMNeYGNrZRj9YRGbBq+13B9p4DyYsG1pwqRmOmlkry31gryUYtRJC1sMg==
  template:
    metadata:
      name: airtrail
      namespace: airtrail
