---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
  namespace: voice
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: whisper
  template:
    metadata:
      labels:
        app: whisper
    spec:
      containers:
        - name: whisper
          image: docker.io/rhasspy/wyoming-whisper:3.8.1@sha256:ba6fcb6056ebe237d15a325381763a80af2fc8fcedaa04f6a714a7375eb20d80
          args:
            - "--model"
            - "small-int8"
            - "--language"
            - "it"
            - "--uri"
            - "tcp://0.0.0.0:10300"
            - "--data-dir"
            - "/data"
            - "--download-dir"
            - "/data"
          env:
            - name: HF_HUB_CACHE
              value: /data/hf-cache
          ports:
            - name: wyoming
              containerPort: 10300
              protocol: TCP
          volumeMounts:
            - name: whisper-data
              mountPath: /data
          readinessProbe:
            tcpSocket:
              port: wyoming
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: wyoming
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: whisper-data
          persistentVolumeClaim:
            claimName: whisper-data
