---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-data
  namespace: voice
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-crypto-global
  resources:
    requests:
      storage: 1Gi
