---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wger-static
  namespace: wger
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-crypto-global
  resources:
    requests:
      storage: 500Mi
