---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wger
  namespace: wger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wger
  template:
    metadata:
      labels:
        app: wger
    spec:
      containers:
        - name: wger
          image: docker.io/wger/server:2.6-dev@sha256:d61c8a5b5821c45203656406acd35ffa9b1a6e5ad5315d775e7fd4d7bc90fd22
          volumeMounts:
            - name: wger-media
              mountPath: /home/wger/media/
            - name: wger-static
              mountPath: /home/wger/static/
          envFrom:
            - configMapRef:
                name: wger
            - secretRef:
                name: wger
      volumes:
        - name: wger-media
          persistentVolumeClaim:
            claimName: wger-media
        - name: wger-static
          persistentVolumeClaim:
            claimName: wger-static
