---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wger-nginx
  namespace: wger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wger-nginx
  template:
    metadata:
      labels:
        app: wger-nginx
    spec:
      containers:
        - name: wger-nginx
          image: docker.io/library/nginx:1.29.4@sha256:ca871a86d45a3ec6864dc45f014b11fe626145569ef0e74deaffc95a3b15b430
          volumeMounts:
            - name: wger-media
              mountPath: /usr/share/nginx/html/media/
            - name: wger-static
              mountPath: /usr/share/nginx/html/static/
          envFrom:
            - configMapRef:
                name: wger-nginx
      volumes:
        - name: wger-media
          persistentVolumeClaim:
            claimName: wger-media
        - name: wger-static
          persistentVolumeClaim:
            claimName: wger-static
