---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wger
  namespace: wger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wger
  template:
    metadata:
      labels:
        app: wger
    spec:
      containers:
        - name: wger
          image: docker.io/wger/server:2.7.0@sha256:eb6e30666ae3058f3094b6030ab661fa3062c9e2ab33c72b554031acf37a3104
          volumeMounts:
            - name: wger-media
              mountPath: /home/wger/media/
            - name: wger-static
              mountPath: /home/wger/static/
          envFrom:
            - configMapRef:
                name: wger
            - secretRef:
                name: wger
      volumes:
        - name: wger-media
          persistentVolumeClaim:
            claimName: wger-media
        - name: wger-static
          persistentVolumeClaim:
            claimName: wger-static
