---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wger
  namespace: wger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wger
  template:
    metadata:
      labels:
        app: wger
    spec:
      containers:
        - name: wger
          image: docker.io/wger/server:2.5-dev@sha256:a65809d3df3cec7fb86fd2ed6fb9c88689a51eae3ba9fb87408099c3741b6b6b
          volumeMounts:
            - name: wger-media
              mountPath: /home/wger/media/
            - name: wger-static
              mountPath: /home/wger/static/
          envFrom:
            - configMapRef:
                name: wger
            - secretRef:
                name: wger
      volumes:
        - name: wger-media
          persistentVolumeClaim:
            claimName: wger-media
        - name: wger-static
          persistentVolumeClaim:
            claimName: wger-static
