---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  sources:
    - repoURL: https://gitea.47fc5c.com/fraccs/homelab.git
      targetRevision: HEAD
      path: kubernetes/k3s-01/workloads/cert-manager
    - repoURL: https://gitea.47fc5c.com/fraccs/homelab.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://charts.jetstack.io/
      chart: cert-manager
      targetRevision: v1.18.2
      helm:
        valueFiles:
          - $values/kubernetes/k3s-01/workloads/cert-manager/values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
