---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app: cert-manager
