---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cdio
  namespace: cdio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdio
  template:
    metadata:
      labels:
        app: cdio
    spec:
      containers:
        - name: cdio
          image: docker.io/linuxserver/changedetection.io:0.54.10@sha256:e00e3759b506586d998e06ccd7e66a5efb2d4361d3b5578ea04bc4b672061347
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: cdio
              mountPath: /config
          envFrom:
            - configMapRef:
                name: cdio
      volumes:
        - name: cdio
          persistentVolumeClaim:
            claimName: cdio
