---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cdio
  namespace: cdio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdio
  template:
    metadata:
      labels:
        app: cdio
    spec:
      containers:
        - name: cdio
          image: docker.io/linuxserver/changedetection.io:0.54.9@sha256:c05a1be65a52973e37c6ca966ab74317529b6dec8448cd714bc4f1c7255a40ad
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: cdio
              mountPath: /config
          envFrom:
            - configMapRef:
                name: cdio
      volumes:
        - name: cdio
          persistentVolumeClaim:
            claimName: cdio
