---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cdio
  namespace: cdio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdio
  template:
    metadata:
      labels:
        app: cdio
    spec:
      containers:
        - name: cdio
          image: docker.io/linuxserver/changedetection.io:0.54.1@sha256:7705c9320504acb22d85309788ce029b603c4d2ac90351451ae7619fdc2dbc12
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: cdio
              mountPath: /config
          envFrom:
            - configMapRef:
                name: cdio
      volumes:
        - name: cdio
          persistentVolumeClaim:
            claimName: cdio
