---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  sources:
    - repoURL: https://gitea.47fc5c.com/fraccs/homelab.git
      targetRevision: HEAD
      path: kubernetes/k3s-01/workloads/gitea
    - repoURL: https://gitea.47fc5c.com/fraccs/homelab.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://dl.gitea.com/charts/
      chart: gitea
      targetRevision: 11.0.1
      helm:
        valueFiles:
          - $values/kubernetes/k3s-01/workloads/gitea/values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
