---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea
  namespace: gitea
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-crypto-global
  resources:
    requests:
      storage: 1Gi
