---
namespace: gitea

global:
  imageRegistry: docker.io

image:
  repository: gitea/gitea

gitea:
  additionalConfigSources:
    - configMap:
        name: gitea
    - secret:
        secretName: gitea-config
  admin:
    existingSecret: gitea-admin
  metrics:
    enabled: true

replicaCount: 2

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

persistence:
  enabled: true
  create: false
  claimName: gitea
  accessModes:
    - ReadWriteMany

# signing:
#   enabled: true
#   gpgHome: /data/git/.gnupg
#   existingSecret: gitea-pgp

actions:
  enabled: true
  provisioning:
    enabled: true

postgresql-ha:
  enabled: false

redis-cluster:
  enabled: false
