---
global:
  imageRegistry: "docker.io"

namespace: "gitea"

replicaCount: 1

strategy:
  type: "RollingUpdate"
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

clusterDomain: k3s-01.47fc5c.com

image:
  registry: "docker.io"
  repository: gitea/gitea
  pullPolicy: IfNotPresent
  rootless: true

persistence:
  enabled: true
  create: false
  claimName: gitea
  accessModes:
    - ReadWriteMany

gitea:
  admin:
    existingSecret: gitea-admin
  metrics:
    enabled: false
  additionalConfigSources:
    - configMap:
        name: gitea
    - secret:
        secretName: gitea-config

valkey-cluster:
  enabled: false

valkey:
  enabled: false

postgresql-ha:
  enabled: false

postgresql:
  enabled: false

# By default, removed or moved settings that still remain in a user defined values.yaml will cause Helm to fail running the install/update.
checkDeprecation: true
test:
  enabled: true
  image:
    name: busybox
    tag: latest
